"""Extract gandalf-ID'd entries from per-reason attack files into staging.

Gandalf samples were ingested and categorized across reason files.
This reconstitutes them as a standalone source for the ProtectAI recipe.

Usage: python scripts/sources/extract_gandalf_staging.py
"""
import sys
import yaml
from pathlib import Path

sys.stdout.reconfigure(encoding='utf-8')

REASON_FILES = [
    "schema/eval/malicious/instruction_override_attacks.yaml",
    "schema/eval/malicious/constraint_bypass_attacks.yaml",
    "schema/eval/malicious/meta_probe_attacks.yaml",
    "schema/eval/malicious/obfuscation_curated_attacks.yaml",
    "schema/eval/malicious/privilege_escalation_attacks.yaml",
    "schema/eval/malicious/roleplay_jailbreak_attacks.yaml",
    "schema/eval/malicious/unclassified_attacks.yaml",
]

try:
    loader = yaml.CSafeLoader
except AttributeError:
    loader = yaml.SafeLoader


def main():
    seen_ids = set()
    cases = []

    for fpath in REASON_FILES:
        p = Path(fpath)
        if not p.exists():
            print(f"  SKIP {fpath} (not found)", file=sys.stderr)
            continue
        with open(p, 'r', encoding='utf-8') as f:
            data = yaml.load(f, Loader=loader)
        if not data:
            continue
        count = 0
        for item in data:
            item_id = item.get('id', '')
            if item_id.startswith('gandalf-') and item_id not in seen_ids:
                seen_ids.add(item_id)
                cases.append(item)
                count += 1
        if count:
            print(f"  {p.name}: {count} gandalf entries", file=sys.stderr)

    # Sort by ID for determinism
    cases.sort(key=lambda x: x.get('id', ''))

    out = Path("schema/eval/staging/opensource_gandalf_attacks.yaml")
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, 'w', encoding='utf-8') as f:
        f.write(
            "# Lakera/gandalf_ignore_instructions — injection cases\n"
            "# Source: https://huggingface.co/datasets/Lakera/gandalf_ignore_instructions\n"
            f"# Extracted from per-reason attack files ({len(cases)} unique entries)\n"
            "# Auto-generated by scripts/sources/extract_gandalf_staging.py\n\n"
        )
        yaml.dump(cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"\nWrote {len(cases)} gandalf entries to {out}", file=sys.stderr)


if __name__ == '__main__':
    main()
