# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Download DhruvTre/jailbreakbench-paraphrase-2025-08 from HuggingFace
and convert to parapet eval YAML format.

Source: https://huggingface.co/datasets/DhruvTre/jailbreakbench-paraphrase-2025-08
License: MIT

115 paraphrased variants of JailbreakBench prompts (56 harmful, 59 benign).
Useful for testing robustness to semantic-preserving rewrites.
"""

import requests
import yaml
import sys

API = "https://datasets-server.huggingface.co/rows"
DATASET = "DhruvTre/jailbreakbench-paraphrase-2025-08"
CONFIG = "default"
SPLIT = "test"


BATCH = 100


def fetch_all_rows():
    rows = []
    offset = 0
    while True:
        resp = requests.get(
            API,
            params={
                "dataset": DATASET,
                "config": CONFIG,
                "split": SPLIT,
                "offset": offset,
                "length": BATCH,
            },
            timeout=30,
        )
        resp.raise_for_status()
        data = resp.json()
        batch = data.get("rows", [])
        if not batch:
            break
        for item in batch:
            row = item.get("row", {})
            rows.append(
                {
                    "prompt": row.get("prompt", ""),
                    "label": row.get("label", 0),
                    "original_prompt": row.get("original_prompt", ""),
                    "prompt_id": row.get("prompt_id", ""),
                }
            )
        print(f"  fetched {len(rows)} rows so far...", file=sys.stderr)
        offset += BATCH
        if len(batch) < BATCH:
            break
    return rows


def main():
    print("Fetching jailbreakbench-paraphrase-2025-08...", file=sys.stderr)
    rows = fetch_all_rows()
    print(f"Total rows: {len(rows)}", file=sys.stderr)

    attacks = []
    benign = []
    for i, row in enumerate(rows):
        text = row["prompt"].strip()
        if not text:
            continue
        case = {
            "id": f"jbb-para-{i:03d}",
            "layer": "l3_inbound",
            "label": "malicious" if row["label"] == 1 else "benign",
            "description": f"JBB paraphrase {row['prompt_id']}",
            "content": text,
        }
        if row["label"] == 1:
            attacks.append(case)
        else:
            benign.append(case)

    print(f"Attacks: {len(attacks)}, Benign: {len(benign)}", file=sys.stderr)

    header_base = (
        "# DhruvTre/jailbreakbench-paraphrase-2025-08\n"
        "# Source: https://huggingface.co/datasets/DhruvTre/jailbreakbench-paraphrase-2025-08\n"
        "# License: MIT\n"
        "# Auto-generated by scripts/fetch_jbb_paraphrase.py\n"
    )

    attack_path = "schema/eval/opensource_jbb_paraphrase_attacks.yaml"
    with open(attack_path, "w", encoding="utf-8") as f:
        f.write(header_base.replace("paraphrase-2025-08\n#", "paraphrase-2025-08 — harmful\n#", 1) + "\n")
        yaml.dump(attacks, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"Wrote {len(attacks)} attack cases to {attack_path}", file=sys.stderr)

    benign_path = "schema/eval/opensource_jbb_paraphrase_benign.yaml"
    with open(benign_path, "w", encoding="utf-8") as f:
        f.write(header_base.replace("paraphrase-2025-08\n#", "paraphrase-2025-08 — benign\n#", 1) + "\n")
        yaml.dump(benign, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"Wrote {len(benign)} benign cases to {benign_path}", file=sys.stderr)

    print("Done.", file=sys.stderr)


if __name__ == "__main__":
    main()
