# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Download reshabhs/SPML_Chatbot_Prompt_Injection from HuggingFace
and convert to parapet eval YAML format.

Source: https://huggingface.co/datasets/reshabhs/SPML_Chatbot_Prompt_Injection
Paper:  https://arxiv.org/abs/2402.11755
License: MIT

16K+ labeled prompts (injection vs benign) with severity degree (0-10).
Each row has a system prompt context, user prompt, and binary label.

Schema:
  {System Prompt, User Prompt, Prompt injection (0/1), Degree (0-10), Source}

We extract "User Prompt" as content. Binary label maps to malicious/benign.
"""

import sys

import requests
import yaml

API = "https://datasets-server.huggingface.co/rows"
DATASET = "reshabhs/SPML_Chatbot_Prompt_Injection"
CONFIG = "default"
SPLIT = "train"
MAX_ROWS = 4000  # Cap total (attacks + benign)
BATCH = 100


def fetch_rows():
    """Fetch rows from HuggingFace dataset API."""
    rows = []
    offset = 0
    while len(rows) < MAX_ROWS:
        length = min(BATCH, MAX_ROWS - len(rows))
        resp = requests.get(
            API,
            params={
                "dataset": DATASET,
                "config": CONFIG,
                "split": SPLIT,
                "offset": offset,
                "length": length,
            },
            timeout=30,
        )
        resp.raise_for_status()
        data = resp.json()
        batch = data.get("rows", [])
        if not batch:
            break
        for item in batch:
            row = item.get("row", {})
            rows.append({
                "prompt": row.get("User Prompt", ""),
                "label": row.get("Prompt injection", 0),
                "degree": row.get("Degree", 0),
            })
        print(f"  fetched {len(rows)} rows so far...", file=sys.stderr)
        offset += length
        if len(batch) < length:
            break
    return rows


def write_yaml(cases, path, header):
    """Write cases to YAML with header comment."""
    with open(path, "w", encoding="utf-8") as f:
        f.write(header + "\n\n")
        yaml.dump(cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"  Wrote {len(cases)} cases to {path}", file=sys.stderr)


def main():
    print("Fetching reshabhs/SPML_Chatbot_Prompt_Injection...", file=sys.stderr)
    rows = fetch_rows()
    print(f"Total rows fetched: {len(rows)}", file=sys.stderr)

    attacks = []
    benign = []
    for i, row in enumerate(rows):
        text = row["prompt"].strip()
        if not text:
            continue
        case = {
            "id": f"spml-{i:04d}",
            "layer": "l1",
            "label": "malicious" if row["label"] == 1 else "benign",
            "description": f"SPML train row {i} (degree={row['degree']})",
            "content": text,
        }
        if row["label"] == 1:
            attacks.append(case)
        else:
            benign.append(case)

    print(f"Attacks: {len(attacks)}, Benign: {len(benign)}", file=sys.stderr)

    header_base = (
        "# reshabhs/SPML_Chatbot_Prompt_Injection — {kind}\n"
        "# Source: https://huggingface.co/datasets/reshabhs/SPML_Chatbot_Prompt_Injection\n"
        "# Paper: https://arxiv.org/abs/2402.11755\n"
        "# License: MIT\n"
        "# 16K+ prompts with injection labels and severity degree.\n"
        "# Auto-generated by scripts/fetch_spml.py"
    )

    write_yaml(
        attacks,
        "schema/eval/opensource_spml_attacks.yaml",
        header_base.format(kind="attacks (label=1)"),
    )
    write_yaml(
        benign,
        "schema/eval/opensource_spml_benign.yaml",
        header_base.format(kind="benign (label=0)"),
    )
    print("Done.", file=sys.stderr)


if __name__ == "__main__":
    main()
