# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Download HuggingFaceH4/no_robots from HuggingFace
and convert to parapet eval YAML format.

Source: https://huggingface.co/datasets/HuggingFaceH4/no_robots
10K high-quality human-written instructions across categories.
All benign. Used by ProtectAI for prompt injection detection training (negative class).
"""

from datasets import load_dataset
import yaml
import sys


def main():
    print("Loading HuggingFaceH4/no_robots...", file=sys.stderr)
    ds = load_dataset("HuggingFaceH4/no_robots", split="train")
    print(f"Total rows: {len(ds)}", file=sys.stderr)

    cases = []
    seen = set()
    for i, row in enumerate(ds):
        # no_robots has "messages" format — extract the first user message
        messages = row.get("messages", [])
        text = ""
        for msg in messages:
            if msg.get("role") == "user":
                text = (msg.get("content") or "").strip()
                break
        if not text:
            text = (row.get("prompt") or row.get("instruction") or "").strip()
        if not text or text in seen:
            continue
        seen.add(text)
        category = row.get("category", "unknown")
        cases.append({
            "id": f"no-robots-{i:04d}",
            "layer": "l1",
            "label": "benign",
            "description": f"no_robots: {category}",
            "content": text,
        })

    print(f"Benign cases (deduplicated): {len(cases)}", file=sys.stderr)
    path = "schema/eval/opensource_no_robots_benign.yaml"
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "# HuggingFaceH4/no_robots — human-written instructions (all benign)\n"
            "# Source: https://huggingface.co/datasets/HuggingFaceH4/no_robots\n"
            "# Auto-generated by scripts/fetch_no_robots.py\n\n"
        )
        yaml.dump(cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"  wrote {len(cases)} cases to {path}", file=sys.stderr)


if __name__ == "__main__":
    main()
