# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Download iamtarun/code_instructions_120k_alpaca from HuggingFace
and convert to parapet eval YAML format.

Source: https://huggingface.co/datasets/iamtarun/code_instructions_120k_alpaca
License: Apache-2.0

122K code instruction prompts across many languages and paradigms.
Sampled to 15K for benign training data — diverse code vocabulary
helps prevent false positives on developer prompts.

Requires: pip install datasets
"""

import random
import sys

import yaml

MAX_SAMPLES = 15000
SEED = 42


def main():
    from datasets import load_dataset

    print("Loading iamtarun/code_instructions_120k_alpaca...", file=sys.stderr)
    ds = load_dataset("iamtarun/code_instructions_120k_alpaca", split="train")
    print(f"  Loaded {len(ds)} rows", file=sys.stderr)

    rows = []
    for row in ds:
        instruction = (row.get("instruction") or "").strip()
        inp = (row.get("input") or "").strip()
        if not instruction:
            continue
        text = f"{instruction}\n{inp}".strip() if inp else instruction
        rows.append(text)

    # Sample
    if len(rows) > MAX_SAMPLES:
        rng = random.Random(SEED)
        rows = rng.sample(rows, MAX_SAMPLES)

    print(f"  Selected {len(rows)} samples", file=sys.stderr)

    cases = []
    for i, text in enumerate(rows):
        cases.append({
            "id": f"codeinst-{i:05d}",
            "layer": "l1",
            "label": "benign",
            "description": f"code_instructions_120k code instruction",
            "content": text,
        })

    path = "schema/eval/opensource_code_instructions_benign.yaml"
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "# iamtarun/code_instructions_120k_alpaca — benign code instructions\n"
            "# Source: https://huggingface.co/datasets/iamtarun/code_instructions_120k_alpaca\n"
            "# License: Apache-2.0\n"
            f"# {len(cases)} code instruction prompts (sampled from 122K) for FP reduction.\n"
            "# Auto-generated by scripts/fetch_code_instructions.py\n\n"
        )
        yaml.dump(cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"  Wrote {len(cases)} cases to {path}", file=sys.stderr)
    print("Done.", file=sys.stderr)


if __name__ == "__main__":
    main()
