# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Download leolee99/NotInject from HuggingFace
and convert to parapet eval YAML format.

Source: https://huggingface.co/datasets/leolee99/NotInject
Paper:  https://arxiv.org/abs/2410.22770
License: MIT

339 benign prompts containing trigger words (ignore, jailbreak, execute, etc.)
that over-eager injection detectors may falsely flag. Three splits by trigger
word count: NotInject_one (1 word), NotInject_two (2), NotInject_three (3).
"""

import requests
import yaml
import sys

API = "https://datasets-server.huggingface.co/rows"
DATASET = "leolee99/NotInject"
CONFIG = "default"
SPLITS = ["NotInject_one", "NotInject_two", "NotInject_three"]
BATCH = 100


def fetch_split(split_name):
    rows = []
    offset = 0
    while True:
        resp = requests.get(
            API,
            params={
                "dataset": DATASET,
                "config": CONFIG,
                "split": split_name,
                "offset": offset,
                "length": BATCH,
            },
            timeout=30,
        )
        resp.raise_for_status()
        data = resp.json()
        batch = data.get("rows", [])
        if not batch:
            break
        for item in batch:
            rows.append(item.get("row", {}))
        offset += len(batch)
        if len(batch) < BATCH:
            break
    return rows


def main():
    print("Fetching leolee99/NotInject...", file=sys.stderr)

    cases = []
    seen = set()

    for split_name in SPLITS:
        print(f"  Split: {split_name}...", file=sys.stderr)
        rows = fetch_split(split_name)
        count = 0
        for row in rows:
            text = str(row.get("prompt") or "").strip()
            category = row.get("category", "")
            words = row.get("word_list", [])
            if not text or len(text) < 10:
                continue
            if text in seen:
                continue
            seen.add(text)

            cases.append({
                "id": f"notinject-{len(cases):04d}",
                "layer": "l1",
                "label": "benign",
                "description": f"NotInject {split_name} cat={category} triggers={','.join(words)}",
                "content": text,
            })
            count += 1
        print(f"    {count} cases", file=sys.stderr)

    print(f"\nTotal: {len(cases)} benign cases", file=sys.stderr)

    path = "schema/eval/opensource_notinject_benign.yaml"
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "# leolee99/NotInject — benign prompts with injection trigger words\n"
            "# Source: https://huggingface.co/datasets/leolee99/NotInject\n"
            "# Paper: https://arxiv.org/abs/2410.22770 (InjecGuard)\n"
            "# License: MIT\n"
            f"# {len(cases)} hard-negative benign cases for FP reduction\n"
            "# Auto-generated by scripts/fetch_notinject.py\n\n"
        )
        yaml.dump(cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"Wrote {len(cases)} cases to {path}", file=sys.stderr)
    print("Done.", file=sys.stderr)


if __name__ == "__main__":
    main()
