# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Download JailbreakV-28K/JailBreakV-28k from HuggingFace
and convert to parapet eval YAML format.

Source: https://huggingface.co/datasets/JailbreakV-28K/JailBreakV-28k
License: MIT

Uses the mini split (280 rows) for eval — a curated representative subset
of the full 28K multimodal jailbreak dataset.  All rows are attacks
(no benign split); text-only jailbreak queries are extracted.
"""

import requests
import yaml
import sys

API = "https://datasets-server.huggingface.co/rows"
DATASET = "JailbreakV-28K/JailBreakV-28k"
CONFIG = "JailBreakV_28K"
SPLIT = "mini_JailBreakV_28K"
BATCH = 100


def fetch_all_rows():
    rows = []
    offset = 0
    while True:
        resp = requests.get(
            API,
            params={
                "dataset": DATASET,
                "config": CONFIG,
                "split": SPLIT,
                "offset": offset,
                "length": BATCH,
            },
            timeout=30,
        )
        resp.raise_for_status()
        data = resp.json()
        batch = data.get("rows", [])
        if not batch:
            break
        for item in batch:
            row = item.get("row", {})
            rows.append(
                {
                    "jailbreak_query": row.get("jailbreak_query", ""),
                    "format": row.get("format", ""),
                    "policy": row.get("policy", ""),
                }
            )
        print(f"  fetched {len(rows)} rows so far...", file=sys.stderr)
        offset += BATCH
        if len(batch) < BATCH:
            break
    return rows


def main():
    print("Fetching JailbreakV-28K mini split...", file=sys.stderr)
    rows = fetch_all_rows()
    print(f"Total rows: {len(rows)}", file=sys.stderr)

    attack_cases = []
    for i, row in enumerate(rows):
        text = row["jailbreak_query"].strip()
        if not text:
            continue
        attack_cases.append(
            {
                "id": f"jailbreakv-{i:04d}",
                "layer": "l3_inbound",
                "label": "malicious",
                "description": f"JailbreakV-28K mini: {row['format']} / {row['policy']}",
                "content": text,
            }
        )

    print(f"Attack cases: {len(attack_cases)}", file=sys.stderr)

    path = "schema/eval/opensource_jailbreakv_attacks.yaml"
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "# JailbreakV-28K/JailBreakV-28k — mini split (all attacks)\n"
            "# Source: https://huggingface.co/datasets/JailbreakV-28K/JailBreakV-28k\n"
            "# License: MIT\n"
            "# Auto-generated by scripts/fetch_jailbreakv.py\n\n"
        )
        yaml.dump(attack_cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"Wrote {len(attack_cases)} cases to {path}", file=sys.stderr)
    print("Done.", file=sys.stderr)


if __name__ == "__main__":
    main()
