# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Convert local TheWall dataset:
  prompt-injection-attack-detection-multilingual

Input:
  TheWall/prompt-injection-attack-detection-multilingual/data/{train,test}.parquet

Output:
  schema/eval/staging/thewall_prompt_injection_attack_detection_multilingual_attacks.yaml
  schema/eval/staging/thewall_prompt_injection_attack_detection_multilingual_benign.yaml

This dataset is binary-labeled (0=safe, 1=injection) and includes a `source` field.
Language is not explicit per row, so we attach a script-based `lang_guess`.
"""

from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

import pandas as pd
import yaml

ROOT = Path(__file__).resolve().parents[1]
THEWALL = ROOT.parent / "TheWall"
DATASET_DIR = THEWALL / "prompt-injection-attack-detection-multilingual" / "data"
TRAIN_FILE = DATASET_DIR / "train-00000-of-00001.parquet"
TEST_FILE = DATASET_DIR / "test-00000-of-00001.parquet"
OUT_ATTACKS = ROOT / "schema" / "eval" / "staging" / "thewall_prompt_injection_attack_detection_multilingual_attacks.yaml"
OUT_BENIGN = ROOT / "schema" / "eval" / "staging" / "thewall_prompt_injection_attack_detection_multilingual_benign.yaml"

RX_CJK = re.compile(r"[\u4e00-\u9fff]")
RX_ARABIC = re.compile(r"[\u0600-\u06ff]")
RX_CYRILLIC = re.compile(r"[А-Яа-яЁё]")
RX_DEVANAGARI = re.compile(r"[\u0900-\u097f]")
RX_THAI = re.compile(r"[\u0e00-\u0e7f]")
RX_LATIN = re.compile(r"[A-Za-z]")


def lang_guess(text: str) -> str:
    if RX_CJK.search(text):
        return "zh"
    if RX_ARABIC.search(text):
        return "ar"
    if RX_CYRILLIC.search(text):
        return "ru"
    if RX_DEVANAGARI.search(text):
        return "hi"
    if RX_THAI.search(text):
        return "th"
    if RX_LATIN.search(text):
        return "latin"
    return "unknown"


def make_case(prefix: str, idx: int, text: str, label: int, source: str) -> dict[str, str]:
    guessed = lang_guess(text)
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()[:10]
    return {
        "id": f"{prefix}-{idx:05d}-{digest}",
        "layer": "l1",
        "label": "malicious" if label == 1 else "benign",
        "description": f"octavio-multilingual source={source} lang_guess={guessed}",
        "content": text,
    }


def dump_yaml(path: Path, rows: list[dict[str, str]], header: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write(header + "\n\n")
        yaml.safe_dump(rows, f, sort_keys=False, allow_unicode=True)


def main() -> None:
    if not TRAIN_FILE.exists() or not TEST_FILE.exists():
        raise SystemExit(f"Dataset files not found under {DATASET_DIR}")

    train = pd.read_parquet(TRAIN_FILE)
    test = pd.read_parquet(TEST_FILE)
    frame = pd.concat([train, test], ignore_index=True)

    required = {"text", "label"}
    missing = required - set(frame.columns)
    if missing:
        raise SystemExit(f"Missing required columns: {sorted(missing)}")

    if "source" not in frame.columns:
        frame["source"] = "octavio-multilingual"

    attacks: list[dict[str, str]] = []
    benign: list[dict[str, str]] = []
    seen: set[tuple[int, str]] = set()

    for idx, row in frame.iterrows():
        text = str(row.get("text") or "").strip()
        if not text:
            continue
        label = int(row.get("label", 0))
        source = str(row.get("source") or "octavio-multilingual").strip() or "octavio-multilingual"
        key = (label, text)
        if key in seen:
            continue
        seen.add(key)
        case = make_case("octavio", idx, text, label, source)
        if label == 1:
            attacks.append(case)
        else:
            benign.append(case)

    header_base = (
        "# TheWall local dataset: prompt-injection-attack-detection-multilingual ({kind})\n"
        "# Source: https://huggingface.co/datasets/Octavio-Santana/prompt-injection-attack-detection-multilingual\n"
        "# Labels: 1=injection, 0=safe\n"
        "# Includes per-row source and script-based lang_guess in description\n"
        "# Auto-generated by scripts/fetch_octavio_multilingual.py"
    )

    dump_yaml(OUT_ATTACKS, attacks, header_base.format(kind="attacks"))
    dump_yaml(OUT_BENIGN, benign, header_base.format(kind="benign"))

    print(f"Wrote attacks={len(attacks)} to {OUT_ATTACKS}", file=sys.stderr)
    print(f"Wrote benign={len(benign)} to {OUT_BENIGN}", file=sys.stderr)


if __name__ == "__main__":
    main()
