# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Download HuggingFaceH4/instruction-dataset from HuggingFace
and convert to parapet eval YAML format.

Source: https://huggingface.co/datasets/HuggingFaceH4/instruction-dataset
Instruction-following dataset curated by HuggingFace. All benign.
Used by ProtectAI for prompt injection detection training (negative class).

Samples up to 2000 entries if dataset is larger.
"""

from datasets import load_dataset
import random
import yaml
import sys

MAX_SAMPLES = 2000


def main():
    print("Loading HuggingFaceH4/instruction-dataset...", file=sys.stderr)
    try:
        ds = load_dataset("HuggingFaceH4/instruction-dataset", split="train")
    except ValueError:
        ds = load_dataset("HuggingFaceH4/instruction-dataset", split="test")
    print(f"Total rows: {len(ds)}", file=sys.stderr)

    cases = []
    seen = set()
    for i, row in enumerate(ds):
        text = (row.get("prompt") or row.get("instruction") or row.get("text") or "").strip()
        if not text or text in seen:
            continue
        seen.add(text)
        cases.append({
            "id": f"hf-instr-{i:04d}",
            "layer": "l1",
            "label": "benign",
            "description": "HF instruction dataset",
            "content": text,
        })

    if len(cases) > MAX_SAMPLES:
        random.seed(42)
        cases = random.sample(cases, MAX_SAMPLES)
        for j, case in enumerate(cases):
            case["id"] = f"hf-instr-{j:04d}"

    print(f"Benign cases: {len(cases)}", file=sys.stderr)
    path = "schema/eval/opensource_hf_instruction_benign.yaml"
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "# HuggingFaceH4/instruction-dataset — instruction-following prompts (all benign)\n"
            "# Source: https://huggingface.co/datasets/HuggingFaceH4/instruction-dataset\n"
            "# Auto-generated by scripts/fetch_hf_instruction.py\n\n"
        )
        yaml.dump(cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"  wrote {len(cases)} cases to {path}", file=sys.stderr)


if __name__ == "__main__":
    main()
