# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Download tatsu-lab/alpaca from HuggingFace
and convert to parapet eval YAML format.

Source: https://huggingface.co/datasets/tatsu-lab/alpaca
License: CC-BY-NC-4.0

52K general instruction prompts. Broad diversity — writing, math,
science, coding, general knowledge. Complements code-heavy benign
datasets with conversational and analytical prompts.

Requires: pip install datasets
"""

import random
import sys

import yaml

MAX_SAMPLES = 12000
SEED = 42


def main():
    from datasets import load_dataset

    print("Loading tatsu-lab/alpaca...", file=sys.stderr)
    ds = load_dataset("tatsu-lab/alpaca", split="train")
    print(f"  Loaded {len(ds)} rows", file=sys.stderr)

    rows = []
    for row in ds:
        instruction = (row.get("instruction") or "").strip()
        inp = (row.get("input") or "").strip()
        if not instruction:
            continue
        text = f"{instruction}\n{inp}".strip() if inp else instruction
        rows.append(text)

    # Sample
    if len(rows) > MAX_SAMPLES:
        rng = random.Random(SEED)
        rows = rng.sample(rows, MAX_SAMPLES)

    print(f"  Selected {len(rows)} samples", file=sys.stderr)

    cases = []
    for i, text in enumerate(rows):
        cases.append({
            "id": f"alpaca-{i:05d}",
            "layer": "l1",
            "label": "benign",
            "description": f"alpaca general instruction",
            "content": text,
        })

    path = "schema/eval/opensource_alpaca_benign.yaml"
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "# tatsu-lab/alpaca — benign general instructions\n"
            "# Source: https://huggingface.co/datasets/tatsu-lab/alpaca\n"
            "# License: CC-BY-NC-4.0\n"
            f"# {len(cases)} general instruction prompts for diverse benign coverage.\n"
            "# Auto-generated by scripts/fetch_alpaca.py\n\n"
        )
        yaml.dump(cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"  Wrote {len(cases)} cases to {path}", file=sys.stderr)
    print("Done.", file=sys.stderr)


if __name__ == "__main__":
    main()
