# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Download HumanCompatibleAI/tensor-trust-data benchmarks from GitHub
and convert to parapet eval YAML format.

Source: https://github.com/HumanCompatibleAI/tensor-trust-data
Paper:  https://arxiv.org/abs/2311.01011
License: MIT

126K+ prompt injection attacks from an online game (Tensor Trust).
Two benchmarks:
  - extraction-robustness: attacks that try to extract the system prompt / access code
  - hijacking-robustness: attacks that try to hijack the model's behavior

Schema per JSONL line:
  {sample_id, pre_prompt, attack, post_prompt, access_code}

We extract the "attack" field as the prompt content. The HF dataset viewer
is broken (schema mismatch), so we fetch directly from GitHub raw.
"""

import json
import random
import sys

import requests
import yaml

EXTRACTION_URL = (
    "https://raw.githubusercontent.com/HumanCompatibleAI/tensor-trust-data"
    "/main/benchmarks/extraction-robustness/v1/extraction_robustness_dataset.jsonl"
)
HIJACKING_URL = (
    "https://raw.githubusercontent.com/HumanCompatibleAI/tensor-trust-data"
    "/main/benchmarks/hijacking-robustness/v1/hijacking_robustness_dataset.jsonl"
)

# Cap per benchmark to keep dataset sizes manageable for training.
MAX_PER_BENCHMARK = 2000
SEED = 42


def fetch_jsonl(url, label):
    """Download a JSONL file and return parsed rows."""
    print(f"  Fetching {label}...", file=sys.stderr)
    resp = requests.get(url, timeout=120)
    resp.raise_for_status()
    rows = []
    for line in resp.text.strip().split("\n"):
        line = line.strip()
        if not line:
            continue
        rows.append(json.loads(line))
    print(f"  {label}: {len(rows)} rows", file=sys.stderr)
    return rows


def sample_rows(rows, max_rows, seed):
    """Deterministically sample if over max."""
    if len(rows) <= max_rows:
        return rows
    rng = random.Random(seed)
    return rng.sample(rows, max_rows)


def rows_to_cases(rows, id_prefix, description_prefix):
    """Convert raw rows to parapet eval YAML cases."""
    cases = []
    for i, row in enumerate(rows):
        attack = row.get("attack", "").strip()
        if not attack:
            continue
        cases.append({
            "id": f"{id_prefix}-{i:04d}",
            "layer": "l1",
            "label": "malicious",
            "description": f"{description_prefix} sample_id={row.get('sample_id', '?')}",
            "content": attack,
        })
    return cases


def write_yaml(cases, path, header):
    """Write cases to YAML with header comment."""
    with open(path, "w", encoding="utf-8") as f:
        f.write(header + "\n\n")
        yaml.dump(cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"  Wrote {len(cases)} cases to {path}", file=sys.stderr)


def main():
    print("Fetching tensor-trust benchmarks from GitHub...", file=sys.stderr)

    extraction_rows = fetch_jsonl(EXTRACTION_URL, "extraction-robustness")
    hijacking_rows = fetch_jsonl(HIJACKING_URL, "hijacking-robustness")

    # Sample to cap size
    extraction_rows = sample_rows(extraction_rows, MAX_PER_BENCHMARK, SEED)
    hijacking_rows = sample_rows(hijacking_rows, MAX_PER_BENCHMARK, SEED)

    extraction_cases = rows_to_cases(
        extraction_rows, "tensortrust-ext", "tensor-trust extraction-robustness"
    )
    hijacking_cases = rows_to_cases(
        hijacking_rows, "tensortrust-hij", "tensor-trust hijacking-robustness"
    )

    print(
        f"\nTotal: {len(extraction_cases)} extraction, "
        f"{len(hijacking_cases)} hijacking",
        file=sys.stderr,
    )

    header_base = (
        "# HumanCompatibleAI/tensor-trust-data — {kind}\n"
        "# Source: https://github.com/HumanCompatibleAI/tensor-trust-data\n"
        "# Paper: https://arxiv.org/abs/2311.01011\n"
        "# License: MIT\n"
        "# 126K+ attacks from online prompt injection game.\n"
        "# Sampled to {max} per benchmark (seed={seed}).\n"
        "# Auto-generated by scripts/fetch_tensor_trust.py"
    )

    write_yaml(
        extraction_cases,
        "schema/eval/opensource_tensortrust_extraction_attacks.yaml",
        header_base.format(
            kind="extraction attacks (prompt/secret extraction)",
            max=MAX_PER_BENCHMARK,
            seed=SEED,
        ),
    )
    write_yaml(
        hijacking_cases,
        "schema/eval/opensource_tensortrust_hijacking_attacks.yaml",
        header_base.format(
            kind="hijacking attacks (behavior override)",
            max=MAX_PER_BENCHMARK,
            seed=SEED,
        ),
    )

    print("Done.", file=sys.stderr)


if __name__ == "__main__":
    main()
