# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Download SafeMTData/SafeMTData Attack_600 from HuggingFace
and convert to parapet eval YAML format.

Source: https://huggingface.co/datasets/SafeMTData/SafeMTData
600 multi-turn attacks using actor-network theory ("crescendo" style).
Each row has multi_turn_queries[] — a sequence of user-side queries
that gradually steer toward a harmful target.

Output format uses messages[] for L4 multi-turn eval.
Note: only user turns are in the dataset (no assistant responses).
"""

from datasets import load_dataset
import yaml
import sys


def main():
    print("Loading SafeMTData/SafeMTData Attack_600...", file=sys.stderr)
    ds = load_dataset("SafeMTData/SafeMTData", "Attack_600", split="Attack_600")
    print(f"Total rows: {len(ds)}", file=sys.stderr)

    cases = []
    for i, row in enumerate(ds):
        queries = row.get("multi_turn_queries", [])
        if not queries or len(queries) < 2:
            continue

        category = row.get("category", "unknown")
        actor = (row.get("actor_name") or "unknown")[:40]

        messages = []
        for q in queries:
            text = str(q).strip() if q else ""
            if text:
                messages.append({"role": "user", "content": text})

        if len(messages) < 2:
            continue

        cases.append({
            "id": f"safemt-{i:03d}",
            "layer": "l4",
            "label": "malicious",
            "description": f"SafeMTData {category}: {actor}",
            "messages": messages,
        })

    print(f"Multi-turn attack cases: {len(cases)}", file=sys.stderr)
    path = "schema/eval/opensource_safemtdata_attacks.yaml"
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "# SafeMTData/SafeMTData Attack_600 — multi-turn crescendo attacks\n"
            "# Source: https://huggingface.co/datasets/SafeMTData/SafeMTData\n"
            "# 600 actor-network attacks with multi_turn_queries (user turns only)\n"
            "# Categories: chemical_biological, illegal, misinformation, harmful, etc.\n"
            "# Auto-generated by scripts/fetch_safemtdata.py\n\n"
        )
        yaml.dump(cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"  wrote {len(cases)} cases to {path}", file=sys.stderr)


if __name__ == "__main__":
    main()
