# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Convert local TheWall dataset:
  sql-injection

Input:
  TheWall/sql-injection/sqli1.json

Output:
  schema/eval/staging/thewall_sql_injection_zh_attacks.yaml

All extracted rows are treated as malicious supplemental attacks.
We extract first `human` turn per conversation to reduce multi-turn leakage and
preserve user-side attack intent phrasing.
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
THEWALL = ROOT.parent / "TheWall"
INPUT_FILE = THEWALL / "sql-injection" / "sqli1.json"
OUT_ATTACKS = ROOT / "schema" / "eval" / "staging" / "thewall_sql_injection_zh_attacks.yaml"


def dump_yaml(path: Path, rows: list[dict[str, str]], header: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write(header + "\n\n")
        yaml.safe_dump(rows, f, sort_keys=False, allow_unicode=True)


def main() -> None:
    if not INPUT_FILE.exists():
        raise SystemExit(f"Missing input dataset: {INPUT_FILE}")

    with INPUT_FILE.open("r", encoding="utf-8") as f:
        payload = json.load(f)
    if not isinstance(payload, list):
        raise SystemExit("Expected top-level list in sqli1.json")

    attacks: list[dict[str, str]] = []
    seen: set[str] = set()

    for idx, item in enumerate(payload):
        if not isinstance(item, dict):
            continue
        conv = item.get("conversations")
        if not isinstance(conv, list):
            continue
        first_human = ""
        for turn in conv:
            if isinstance(turn, dict) and str(turn.get("from", "")).strip().lower() == "human":
                first_human = str(turn.get("value") or "").strip()
                break
        if not first_human:
            continue
        if first_human in seen:
            continue
        seen.add(first_human)
        digest = hashlib.sha256(first_human.encode("utf-8")).hexdigest()[:10]
        attacks.append(
            {
                "id": f"sqli-zh-{idx:05d}-{digest}",
                "layer": "l1",
                "label": "malicious",
                "description": "sql-injection source=sqli1.json lang=zh extract=first_human_turn",
                "content": first_human,
            }
        )

    header = (
        "# TheWall local dataset: sql-injection (attacks)\n"
        "# Source: https://huggingface.co/datasets/Kaveny/sql-injection\n"
        "# Extracted first `human` turn from each conversation\n"
        "# Treated as supplemental malicious cyber-offense surface (ZH)\n"
        "# Auto-generated by scripts/fetch_sql_injection_zh.py"
    )
    dump_yaml(OUT_ATTACKS, attacks, header)
    print(f"Wrote attacks={len(attacks)} to {OUT_ATTACKS}", file=sys.stderr)


if __name__ == "__main__":
    main()
