// Copyright 2026 The Parapet Project
// SPDX-License-Identifier: Apache-2.0

// L2 semantic classifier weights (MiniLM + LR).
//
// Generated by scripts/codegen_l2.py. Do not edit manually.
//
// These are placeholder zeros. Replace with real weights after training
// the LR head on MiniLM embeddings + harness signals.

/// Embedding dimension from all-MiniLM-L6-v2.
pub const EMBEDDING_DIM: usize = 384;

/// Number of L1 harness signal features.
pub const HARNESS_DIM: usize = 5;

/// Total feature dimension: embedding + harness signals.
pub const TOTAL_DIM: usize = EMBEDDING_DIM + HARNESS_DIM;

/// LR weight vector. Length = TOTAL_DIM = 389.
pub const L2_WEIGHTS: [f32; TOTAL_DIM] = [0.0; TOTAL_DIM];

/// LR bias term.
pub const L2_BIAS: f32 = 0.0;

/// StandardScaler mean for the 5 harness signals.
/// Order: raw_score, raw_unquoted_score, raw_squash_score, raw_score_delta, quote_detected.
pub const L2_HARNESS_MEAN: [f32; HARNESS_DIM] = [0.0; HARNESS_DIM];

/// StandardScaler scale (std dev) for the 5 harness signals.
pub const L2_HARNESS_SCALE: [f32; HARNESS_DIM] = [1.0; HARNESS_DIM];
