"""Builds notebooks/truncation_spike_kaggle.ipynb deterministically.

Run from the parapet/ project root:

    python scripts/build_truncation_spike_notebook.py

The notebook is regenerated from the cell definitions below. Edit this script,
not the .ipynb, when changing notebook content. Treat the .ipynb as a generated
artifact: round-trip diffs against this script should be empty.

Pattern matches scripts/build_latency_notebook.py. The truncation policy
module (parapet_runner/truncation.py) is inlined into the notebook at
build time, since the policy code is new and not yet in a pinned public
commit. The parapet-runner package is NOT installed in the notebook —
the policy logic is read from disk and embedded.
"""

from __future__ import annotations

import json
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
TRUNCATION_PY = PROJECT_ROOT / "parapet-runner" / "parapet_runner" / "truncation.py"


def md_cell(cell_id: str, lines: list[str]) -> dict:
    return {
        "cell_type": "markdown",
        "id": cell_id,
        "metadata": {},
        "source": _with_newlines(lines),
    }


def code_cell(cell_id: str, lines: list[str]) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "id": cell_id,
        "metadata": {},
        "outputs": [],
        "source": _with_newlines(lines),
    }


def _with_newlines(lines: list[str]) -> list[str]:
    if not lines:
        return []
    return [line + "\n" for line in lines[:-1]] + [lines[-1]]


def _read_truncation_module() -> list[str]:
    """Read parapet_runner/truncation.py as the notebook's source-of-truth.

    The module is inlined unmodified — same docstrings, same constants, same
    function signatures. Round-trip diff against the .py file should be empty.
    """
    src = TRUNCATION_PY.read_text(encoding="utf-8")
    return src.splitlines()


CELLS = [
    md_cell("00-title", [
        "# Phase 1 truncation-policy spike — MiniLM-L12 on v8 residuals",
        "",
        "Tests 5 truncation policies against the Phase 1 v8 residual artifact",
        "with frozen sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2",
        "+ a balanced logistic regression head. **Ranking only**, not",
        "acceptance evidence.",
        "",
        "## Inputs",
        "",
        "One Kaggle dataset containing `residuals.jsonl` (the §0.1-conformant",
        "Phase 1 export from `parapet-runner/runs/phase1_v8_residuals/`).",
        "Glob-discovered under `/kaggle/input/**/residuals.jsonl`.",
        "",
        "## Discipline",
        "",
        "* Train: rows with `fold_id` in {0,1,2,3}.",
        "* Val: rows with `fold_id == 4`.",
        "* Encoder is FROZEN. Only the linear head is trained per policy.",
        "* No legacy `schema/eval/` YAML enters this notebook. Residuals are the",
        "  sole input.",
        "",
        "## Policies",
        "",
        "| policy | description |",
        "|--------|-------------|",
        "| head_128 | first 128 tokens |",
        "| tail_128 | last 128 tokens |",
        "| head_tail_64_64 | first 64 + last 64, joined with `\" ... \"` |",
        "| suspicious_span_128 | densest 128-token window by attack-trigger keywords |",
        "| full_512 | overlapping 128-token chunks (stride 64), mean-pooled embeddings |",
        "",
        "**Runtime:** GPU recommended (T4). **Internet:** on (for HF model download).",
    ]),
    code_cell("05-config", [
        "# Config knobs. Swap to bench a different candidate; the rest follows.",
        "import glob",
        "",
        'MODEL_ID = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"',
        'RESIDUALS_GLOB = "/kaggle/input/**/residuals.jsonl"',
        "",
        "# Train/val split: by fold_id (matches Phase 1 §0.4 grouped CV discipline).",
        "VAL_FOLD = 4",
        "",
        "# Recall is reported at this fixed FPR.",
        "TARGET_FPR = 0.10",
        "",
        "# Policies to evaluate. Drop entries here to run a subset.",
        "POLICIES = [",
        '    "head_128",',
        '    "tail_128",',
        '    "head_tail_64_64",',
        '    "suspicious_span_128",',
        '    "full_512",',
        "]",
        "",
        "# Encoder batch size. Bumped on GPU; sentence-transformers handles padding.",
        "ENCODER_BATCH_SIZE = 64",
        "",
        "SEED = 42",
        "",
        "# Glob-discover the residuals JSONL. Kaggle's mount path varies",
        "# (e.g. /kaggle/input/datasets/<user>/<slug>/...), so we search.",
        "_matches = glob.glob(RESIDUALS_GLOB, recursive=True)",
        'assert len(_matches) == 1, f"expected exactly one residuals match, got: {_matches}"',
        "RESIDUALS_PATH = _matches[0]",
        "",
        "# Hard guard: refuse legacy eval paths under any circumstance.",
        '_FORBIDDEN = ("schema/eval/l1_holdout", "schema/eval/challenges")',
        "_norm = RESIDUALS_PATH.replace('\\\\', '/')",
        'assert not any(s in _norm for s in _FORBIDDEN), \\',
        '    f"REFUSING: residuals path looks like a legacy eval YAML: {RESIDUALS_PATH!r}"',
        "",
        'print(f"MODEL_ID        = {MODEL_ID}")',
        'print(f"RESIDUALS_PATH  = {RESIDUALS_PATH}")',
        'print(f"VAL_FOLD        = {VAL_FOLD}")',
        'print(f"TARGET_FPR      = {TARGET_FPR}")',
        'print(f"POLICIES        = {POLICIES}")',
    ]),
    code_cell("07-fingerprint", [
        "# Hardware fingerprint mirrors scripts/hardware_fingerprint.py inline so",
        "# the notebook does not depend on parapet/ being on the Kaggle filesystem.",
        "import hashlib, json, os, platform, shutil, subprocess",
        "",
        "def _sha256_text(t):",
        "    return hashlib.sha256(t.encode('utf-8', errors='replace')).hexdigest() if t else None",
        "",
        "def _read(p):",
        "    try: return open(p, encoding='utf-8', errors='replace').read()",
        "    except OSError: return None",
        "",
        "def _run(cmd):",
        "    if shutil.which(cmd[0]) is None: return None",
        "    try:",
        "        r = subprocess.run(cmd, capture_output=True, text=True, timeout=10, check=False)",
        "    except (OSError, subprocess.SubprocessError): return None",
        "    return r.stdout if r.returncode == 0 else None",
        "",
        "_cpuinfo = _read('/proc/cpuinfo') if platform.system()=='Linux' else None",
        "_lscpu   = _run(['lscpu'])         if platform.system()=='Linux' else None",
        "_nvsmi   = _run(['nvidia-smi', '-q', '-x'])",
        "try:",
        "    import torch as _torch",
        "    _torch_ver = _torch.__version__",
        "    _cuda_avail = bool(_torch.cuda.is_available())",
        "    _cuda_dev = _torch.cuda.get_device_name(0) if _cuda_avail else None",
        "except ImportError:",
        "    _torch_ver, _cuda_avail, _cuda_dev = None, False, None",
        "",
        "HARDWARE_FINGERPRINT = {",
        "    'platform': platform.system(),",
        "    'platform_release': platform.release(),",
        "    'platform_machine': platform.machine(),",
        "    'python_version': platform.python_version(),",
        "    'cpu_model': platform.processor() or None,",
        "    'cpu_count_logical': os.cpu_count(),",
        "    'cpuinfo_sha256': _sha256_text(_cpuinfo),",
        "    'lscpu_sha256': _sha256_text(_lscpu),",
        "    'nvsmi_sha256': _sha256_text(_nvsmi),",
        "    'cuda_device': _cuda_dev,",
        "    'cuda_available': _cuda_avail,",
        "    'torch_version': _torch_ver,",
        "}",
        "",
        "_fp_blob = json.dumps(HARDWARE_FINGERPRINT, sort_keys=True).encode('utf-8')",
        "HARDWARE_FINGERPRINT_SHA256 = hashlib.sha256(_fp_blob).hexdigest()",
        "",
        "with open('/kaggle/working/hardware_fingerprint.json', 'w') as _f:",
        "    json.dump(HARDWARE_FINGERPRINT, _f, indent=2, sort_keys=True)",
        "",
        "print(f'hardware_fingerprint_sha256 = {HARDWARE_FINGERPRINT_SHA256}')",
        "print(json.dumps({k: v for k, v in HARDWARE_FINGERPRINT.items() if not k.endswith('_sha256')},",
        "                 indent=2, sort_keys=True))",
    ]),
    code_cell("10-install-deps", [
        "# Kaggle T4 image typically has sentence-transformers, transformers, and",
        "# scikit-learn pre-installed. Pin minimums to fail fast if that ever changes.",
        '!pip install -q "sentence-transformers>=3.0" "transformers>=4.40" "scikit-learn>=1.3"',
    ]),
    md_cell("15-truncation-section", [
        "## Truncation policies (inlined from `parapet_runner/truncation.py`)",
        "",
        "Source-of-truth lives at `parapet-runner/parapet_runner/truncation.py` in",
        "the parapet repo. Inlined here unmodified at notebook-build time. Round-trip",
        "diff against the .py file should be empty.",
    ]),
    code_cell("20-truncation-module", _read_truncation_module()),
    code_cell("25-helpers", [
        "# Helpers mirror parapet-runner/scripts/phase1_truncation_policy_spike.py.",
        "# Kept inline so the notebook is self-contained.",
        "",
        "import json",
        "from pathlib import Path",
        "from typing import Any, Callable",
        "",
        "import numpy as np",
        "",
        "CHUNK_SIZE = 128",
        "CHUNK_STRIDE = 64",
        "FULL_512_TOKEN_BUDGET = 512",
        "",
        "",
        "def load_residuals(path):",
        "    rows = []",
        '    with open(path, "r", encoding="utf-8") as f:',
        "        for line in f:",
        "            line = line.strip()",
        "            if not line:",
        "                continue",
        "            rows.append(json.loads(line))",
        "    return rows",
        "",
        "",
        "def split_by_fold(rows, val_fold):",
        "    train, val = [], []",
        "    for r in rows:",
        "        if r.get('fold_id') == val_fold:",
        "            val.append(r)",
        "        else:",
        "            train.append(r)",
        "    return train, val",
        "",
        "",
        "def label_to_int(lab):",
        "    return 1 if lab == 'malicious' else 0",
        "",
        "",
        "def build_truncated_strings(text, token_ids, offsets, *, policy):",
        "    if policy == 'full_512':",
        "        budget = min(len(token_ids), FULL_512_TOKEN_BUDGET)",
        "        if budget <= CHUNK_SIZE:",
        "            return [text]",
        "        chunks = []",
        "        start = 0",
        "        while start < budget:",
        "            end = min(start + CHUNK_SIZE, budget)",
        "            chunk_text = text[offsets[start][0]:offsets[end - 1][1]]",
        "            if chunk_text.strip():",
        "                chunks.append(chunk_text)",
        "            if end >= budget:",
        "                break",
        "            start += CHUNK_STRIDE",
        "        return chunks or [text]",
        "    truncated_ids = apply_policy(",
        "        policy, token_ids=token_ids, char_offsets=offsets, text=text,",
        "    )",
        "    if not truncated_ids:",
        "        return [text[:1] or ' ']",
        "    if policy == 'head_128':",
        "        end_char = offsets[len(truncated_ids) - 1][1]",
        "        return [text[:end_char]]",
        "    if policy == 'tail_128':",
        "        start_char = offsets[len(token_ids) - len(truncated_ids)][0]",
        "        return [text[start_char:]]",
        "    if policy == 'head_tail_64_64':",
        "        head_n = min(64, len(token_ids))",
        "        tail_n = min(64, len(token_ids) - head_n)",
        "        if tail_n <= 0:",
        "            return [text[:offsets[head_n - 1][1]]]",
        "        head_text = text[:offsets[head_n - 1][1]]",
        "        tail_text = text[offsets[len(token_ids) - tail_n][0]:]",
        "        return [head_text + ' ... ' + tail_text]",
        "    if policy == 'suspicious_span_128':",
        "        n_trunc = len(truncated_ids)",
        "        for s in range(0, len(token_ids) - n_trunc + 1):",
        "            if token_ids[s:s + n_trunc] == truncated_ids:",
        "                return [text[offsets[s][0]:offsets[s + n_trunc - 1][1]]]",
        "        return [text[:offsets[min(n_trunc, len(offsets)) - 1][1]]]",
        '    raise ValueError(f"unknown policy {policy!r}")',
    ]),
    code_cell("30-load-and-split", [
        "rows = load_residuals(RESIDUALS_PATH)",
        'print(f"Loaded {len(rows):,} residual rows")',
        "",
        "train_rows, val_rows = split_by_fold(rows, VAL_FOLD)",
        'print(f"Train (fold != {VAL_FOLD}): {len(train_rows):,} rows")',
        'print(f"Val   (fold == {VAL_FOLD}): {len(val_rows):,} rows")',
        "",
        "from collections import Counter",
        "_train_lab = Counter(r.get('label') for r in train_rows)",
        "_val_lab   = Counter(r.get('label') for r in val_rows)",
        'print(f"Train labels: {dict(_train_lab)}")',
        'print(f"Val labels:   {dict(_val_lab)}")',
        "",
        "_val_lang = Counter(r.get('language') for r in val_rows)",
        "_val_lang_mal = Counter()",
        "for r in val_rows:",
        "    if r.get('label') == 'malicious':",
        "        _val_lang_mal[r.get('language')] += 1",
        'print(f"Val per-lang n / n_malicious:")',
        "for _l, _n in _val_lang.most_common():",
        "    print(f'  {_l}: n={_n} mal={_val_lang_mal.get(_l, 0)}')",
    ]),
    code_cell("40-tokenizer-encoder", [
        "import torch",
        "from transformers import AutoTokenizer",
        "from sentence_transformers import SentenceTransformer",
        "",
        "tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, use_fast=True)",
        "model = SentenceTransformer(MODEL_ID)",
        "_DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'",
        "model = model.to(_DEVICE)",
        "model.eval()",
        "print(f'Encoder loaded on {_DEVICE}')",
        "",
        "def tokenize_fn(text):",
        "    out = tokenizer(",
        "        text or ' ',",
        "        return_offsets_mapping=True,",
        "        add_special_tokens=False,",
        "        truncation=False,",
        "    )",
        "    offsets = [(int(s), int(e)) for s, e in out['offset_mapping']]",
        "    return list(map(int, out['input_ids'])), offsets",
        "",
        "def encoder(texts):",
        "    if not texts:",
        "        return np.zeros((0, 384), dtype=np.float32)",
        "    emb = model.encode(",
        "        texts,",
        "        batch_size=ENCODER_BATCH_SIZE,",
        "        show_progress_bar=False,",
        "        convert_to_numpy=True,",
        "        normalize_embeddings=False,",
        "        device=_DEVICE,",
        "    )",
        "    return emb.astype(np.float32)",
    ]),
    code_cell("50-encode-rows", [
        "# Per-policy encoding. For full_512 we encode multiple chunks per row and",
        "# mean-pool. Embeddings cached in memory (no disk cache on Kaggle).",
        "import time",
        "",
        "def encode_rows_for_policy(rows, policy, *, label):",
        "    embeddings = []",
        "    n = len(rows)",
        "    t0 = time.time()",
        "    for i, r in enumerate(rows):",
        "        text = r.get('content') or ''",
        "        token_ids, offsets = tokenize_fn(text)",
        "        if not token_ids:",
        "            embeddings.append(encoder([' '])[0])",
        "            continue",
        "        chunks = build_truncated_strings(text, token_ids, offsets, policy=policy)",
        "        chunk_emb = encoder(chunks)",
        "        if chunk_emb.shape[0] > 1:",
        "            embeddings.append(chunk_emb.mean(axis=0))",
        "        else:",
        "            embeddings.append(chunk_emb[0])",
        "        if (i + 1) % 1000 == 0:",
        "            elapsed = time.time() - t0",
        "            rate = (i + 1) / max(elapsed, 1e-3)",
        "            print(f'  [{policy}/{label}] {i + 1}/{n} rows ({rate:.0f}/sec)')",
        "    print(f'  [{policy}/{label}] done in {time.time() - t0:.1f}s')",
        "    return np.vstack(embeddings).astype(np.float32)",
        "",
        "ALL_EMBEDDINGS = {}  # policy -> {'train': arr, 'val': arr}",
        "for _policy in POLICIES:",
        "    print(f'\\n=== Encoding {_policy} ===')",
        "    ALL_EMBEDDINGS[_policy] = {",
        "        'train': encode_rows_for_policy(train_rows, _policy, label='train'),",
        "        'val':   encode_rows_for_policy(val_rows,   _policy, label='val'),",
        "    }",
    ]),
    code_cell("60-fit-and-evaluate", [
        "from sklearn.linear_model import LogisticRegression",
        "from sklearn.metrics import roc_auc_score, roc_curve",
        "",
        "train_labels = np.array([label_to_int(r.get('label') or 'benign') for r in train_rows])",
        "val_labels   = np.array([label_to_int(r.get('label') or 'benign') for r in val_rows])",
        "",
        "def recall_at_fpr(y_true, scores, target_fpr):",
        "    fpr, tpr, thr = roc_curve(y_true, scores)",
        "    eligible = fpr <= target_fpr",
        "    if not eligible.any():",
        "        return 0.0, 0.0, float('inf')",
        "    idx = int(np.argmax(np.where(eligible, tpr, -1)))",
        "    return float(tpr[idx]), float(fpr[idx]), float(thr[idx])",
        "",
        "RESULTS = {}",
        "for _policy in POLICIES:",
        "    train_emb = ALL_EMBEDDINGS[_policy]['train']",
        "    val_emb   = ALL_EMBEDDINGS[_policy]['val']",
        "    clf = LogisticRegression(",
        "        class_weight='balanced',",
        "        max_iter=2000,",
        "        random_state=SEED,",
        "        solver='liblinear',",
        "    )",
        "    clf.fit(train_emb, train_labels)",
        "    scores = clf.predict_proba(val_emb)[:, 1]",
        "    if len(np.unique(val_labels)) < 2:",
        "        recall, fpr, thr, auc = 0.0, 0.0, float('inf'), float('nan')",
        "    else:",
        "        recall, fpr, thr = recall_at_fpr(val_labels, scores, TARGET_FPR)",
        "        auc = float(roc_auc_score(val_labels, scores))",
        "",
        "    # Per-language slice",
        "    from collections import defaultdict",
        "    by_lang = defaultdict(list)",
        "    for i, r in enumerate(val_rows):",
        "        by_lang[str(r.get('language') or 'unknown')].append(i)",
        "    per_lang = {}",
        "    for _lang, _idxs in by_lang.items():",
        "        idxs = np.array(_idxs)",
        "        y_l = val_labels[idxs]",
        "        s_l = scores[idxs]",
        "        if len(np.unique(y_l)) < 2:",
        "            per_lang[_lang] = {",
        "                'n': int(len(y_l)), 'n_malicious': int(y_l.sum()),",
        "                'recall_at_fpr': float('nan'), 'roc_auc': float('nan'),",
        "            }",
        "        else:",
        "            r_l, f_l, _ = recall_at_fpr(y_l, s_l, TARGET_FPR)",
        "            per_lang[_lang] = {",
        "                'n': int(len(y_l)), 'n_malicious': int(y_l.sum()),",
        "                'recall_at_fpr': r_l, 'achieved_fpr': f_l,",
        "                'roc_auc': float(roc_auc_score(y_l, s_l)),",
        "            }",
        "",
        "    RESULTS[_policy] = {",
        "        'recall_at_fpr': recall,",
        "        'achieved_fpr': fpr,",
        "        'threshold': thr,",
        "        'roc_auc': auc,",
        "        'n_val': int(len(val_labels)),",
        "        'n_val_malicious': int(val_labels.sum()),",
        "        'per_language': per_lang,",
        "    }",
        "    print(f'{_policy:<22} recall@FPR={recall:.3f} (achieved {fpr:.3f})  AUC={auc:.3f}')",
    ]),
    code_cell("70-summary", [
        "# Rank by recall@FPR (primary) then AUC (tiebreak).",
        "import math, datetime, os",
        "",
        "ranked = sorted(",
        "    RESULTS.items(),",
        "    key=lambda kv: (-kv[1]['recall_at_fpr'], -kv[1]['roc_auc']),",
        ")",
        "",
        "print('\\n=== Ranking ===')",
        "print(f'{\"rank\":>4}  {\"policy\":<22}  {\"recall@FPR\":>12}  {\"AUC\":>8}')",
        "for i, (policy, r) in enumerate(ranked):",
        "    print(f'{i+1:>4}  {policy:<22}  {r[\"recall_at_fpr\"]:>12.3f}  {r[\"roc_auc\"]:>8.3f}')",
        "",
        "summary = {",
        "    'schema_version': 1,",
        "    'created_utc': datetime.datetime.now(datetime.timezone.utc).isoformat(timespec='seconds'),",
        "    'model_id': MODEL_ID,",
        "    'target_fpr': TARGET_FPR,",
        "    'val_fold': VAL_FOLD,",
        "    'n_train': len(train_rows),",
        "    'n_val':   len(val_rows),",
        "    'hardware_fingerprint_sha256': HARDWARE_FINGERPRINT_SHA256,",
        "    'residuals_path': RESIDUALS_PATH,",
        "    'spike_scope': 'ranking only — NOT acceptance evidence',",
        "    'ranking': [",
        "        {",
        "            'rank': i + 1,",
        "            'policy': policy,",
        "            'recall_at_fpr': r['recall_at_fpr'],",
        "            'achieved_fpr': r['achieved_fpr'],",
        "            'roc_auc': r['roc_auc'],",
        "            'n_val_malicious': r['n_val_malicious'],",
        "        }",
        "        for i, (policy, r) in enumerate(ranked)",
        "    ],",
        "    'per_policy': RESULTS,",
        "}",
        "",
        "# Standard JSON cannot encode inf / nan. Sanitize -> None before write.",
        "def _json_safe(o):",
        "    if isinstance(o, dict):  return {k: _json_safe(v) for k, v in o.items()}",
        "    if isinstance(o, list):  return [_json_safe(v) for v in o]",
        "    if isinstance(o, float) and (math.isinf(o) or math.isnan(o)): return None",
        "    return o",
        "",
        "_out = '/kaggle/working/truncation_spike_summary.json'",
        "with open(_out, 'w', encoding='utf-8') as f:",
        "    json.dump(_json_safe(summary), f, indent=2, ensure_ascii=False)",
        "",
        "print(f'\\nSummary written to {_out}  (size={os.path.getsize(_out)} bytes)')",
        "print('Decision rules (from direction.md):')",
        "print('  head_128 within ~1-2 recall points of full_512 -> use head_128')",
        "print('  head_tail_64_64 recovers suffix attacks -> prefer over head-only')",
        "print('  full_512 materially beats all 128-token policies -> MiniLM is slow-lane only')",
        "print('  suspicious_span_128 beats both -> mechanical scan selects what L2 sees')",
    ]),
    code_cell("80-per-language-table", [
        "# Per-language detail per policy. Languages with <2 classes show NaN.",
        "print(f'{\"policy\":<22}  {\"lang\":<4}  {\"n\":>4}  {\"n_mal\":>5}  {\"r@FPR\":>8}  {\"AUC\":>6}')",
        "for policy, r in RESULTS.items():",
        "    for lang, m in sorted(r['per_language'].items()):",
        "        print(f'{policy:<22}  {lang:<4}  {m[\"n\"]:>4}  {m[\"n_malicious\"]:>5}  '",
        "              f'{m.get(\"recall_at_fpr\", float(\"nan\")):>8.3f}  '",
        "              f'{m.get(\"roc_auc\", float(\"nan\")):>6.3f}')",
    ]),
]


def main() -> None:
    nb = {
        "cells": CELLS,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.11"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    out = PROJECT_ROOT / "notebooks" / "truncation_spike_kaggle.ipynb"
    out.write_text(json.dumps(nb, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {out} ({out.stat().st_size} bytes, {len(CELLS)} cells)")


if __name__ == "__main__":
    main()
