# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Download geekyrakshit/prompt-injection-dataset from HuggingFace
and convert to parapet eval YAML format.

Source: https://huggingface.co/datasets/geekyrakshit/prompt-injection-dataset
License: Not declared

534K+ prompts aggregated from deepset/prompt-injections,
xTRam1/safe-guard-prompt-injection, and jayavibhav/prompt-injection.
Binary labels (1=injection, 0=benign).

NOTE: Overlaps with deepset (already in inventory) and xTRam1.
Uses test split, sampled to avoid duplication with smaller datasets.
"""

import requests
import yaml
import sys

API = "https://datasets-server.huggingface.co/rows"
DATASET = "geekyrakshit/prompt-injection-dataset"
CONFIG = "default"
SPLIT = "test"
MAX_ROWS = 2000
BATCH = 100


def fetch_rows():
    rows = []
    offset = 0
    while len(rows) < MAX_ROWS:
        length = min(BATCH, MAX_ROWS - len(rows))
        resp = requests.get(
            API,
            params={
                "dataset": DATASET,
                "config": CONFIG,
                "split": SPLIT,
                "offset": offset,
                "length": length,
            },
            timeout=30,
        )
        resp.raise_for_status()
        data = resp.json()
        batch = data.get("rows", [])
        if not batch:
            break
        for item in batch:
            row = item.get("row", {})
            rows.append(
                {
                    "prompt": row.get("prompt", ""),
                    "label": row.get("label", 0),
                }
            )
        print(f"  fetched {len(rows)} rows so far...", file=sys.stderr)
        offset += length
        if len(batch) < length:
            break
    return rows


def write_yaml(cases, path, header):
    with open(path, "w", encoding="utf-8") as f:
        f.write(header + "\n\n")
        yaml.dump(cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"  Wrote {len(cases)} cases to {path}", file=sys.stderr)


def main():
    print("Fetching geekyrakshit/prompt-injection-dataset (test split)...", file=sys.stderr)
    rows = fetch_rows()
    print(f"Total rows fetched: {len(rows)}", file=sys.stderr)

    attacks = []
    benign = []
    for i, row in enumerate(rows):
        text = row["prompt"].strip()
        if not text:
            continue
        case = {
            "id": f"geekyrakshit-{i:04d}",
            "layer": "l3_inbound",
            "label": "malicious" if row["label"] == 1 else "benign",
            "description": f"geekyrakshit test row {i}",
            "content": text,
        }
        if row["label"] == 1:
            attacks.append(case)
        else:
            benign.append(case)

    print(f"Attacks: {len(attacks)}, Benign: {len(benign)}", file=sys.stderr)

    header_base = (
        "# geekyrakshit/prompt-injection-dataset — {kind}\n"
        "# Source: https://huggingface.co/datasets/geekyrakshit/prompt-injection-dataset\n"
        "# License: Not declared\n"
        "# NOTE: Aggregates deepset + xTRam1 + jayavibhav (partial overlap with existing inventory)\n"
        "# Auto-generated by scripts/fetch_geekyrakshit.py"
    )

    write_yaml(attacks, "schema/eval/opensource_geekyrakshit_attacks.yaml", header_base.format(kind="attacks (label=1)"))
    write_yaml(benign, "schema/eval/opensource_geekyrakshit_benign.yaml", header_base.format(kind="benign (label=0)"))
    print("Done.", file=sys.stderr)


if __name__ == "__main__":
    main()
