# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Download Giskard-AI/prompt-injections from GitHub
and convert to parapet eval YAML format.

Source: https://github.com/Giskard-AI/prompt-injections
35 curated injection prompts: DAN variants, developer mode, hijacking attacks.
All prompts are injection attacks (no benign labels).
Aggregated from garak and PromptInject libraries.
"""

import csv
import io
import requests
import yaml
import sys

RAW_URL = "https://raw.githubusercontent.com/Giskard-AI/prompt-injections/main/prompt_injections.csv"


def main():
    print("Fetching Giskard-AI/prompt-injections from GitHub...", file=sys.stderr)
    resp = requests.get(RAW_URL)
    resp.raise_for_status()

    reader = csv.DictReader(io.StringIO(resp.text))
    cases = []
    for row in reader:
        prompt = row.get("prompt", "").strip()
        if not prompt:
            continue
        idx = row.get("index", len(cases))
        name = row.get("name", "unknown")
        group = row.get("group", "unknown")
        language = row.get("language", "en")
        cases.append({
            "id": f"giskard-{int(idx):03d}",
            "layer": "l3_inbound",
            "label": "malicious",
            "description": f"Giskard {group}: {name} ({language})",
            "content": prompt,
        })

    print(f"Total: {len(cases)} injection prompts", file=sys.stderr)

    path = "schema/eval/opensource_giskard_attacks.yaml"
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "# Giskard-AI/prompt-injections — injection cases\n"
            "# Source: https://github.com/Giskard-AI/prompt-injections\n"
            "# Aggregated from garak and PromptInject libraries\n"
            "# Auto-generated by scripts/fetch_giskard.py\n\n"
        )
        yaml.dump(cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"Wrote {len(cases)} cases to {path}", file=sys.stderr)


if __name__ == "__main__":
    main()
