# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Download hendzh/PromptShield from HuggingFace
and convert to parapet eval YAML format.

Source: https://huggingface.co/datasets/hendzh/PromptShield
License: Apache-2.0
Paper:  https://arxiv.org/abs/2501.15145

43K+ prompts with binary labels (1=injection, 0=benign).
Uses test split for eval (23,516 rows) — sampled to keep eval fast.
"""

import requests
import yaml
import sys

API = "https://datasets-server.huggingface.co/rows"
DATASET = "hendzh/PromptShield"
CONFIG = "default"
SPLIT = "test"
MAX_ROWS = 2000
BATCH = 100


def fetch_rows():
    rows = []
    offset = 0
    while len(rows) < MAX_ROWS:
        length = min(BATCH, MAX_ROWS - len(rows))
        resp = requests.get(
            API,
            params={
                "dataset": DATASET,
                "config": CONFIG,
                "split": SPLIT,
                "offset": offset,
                "length": length,
            },
            timeout=30,
        )
        resp.raise_for_status()
        data = resp.json()
        batch = data.get("rows", [])
        if not batch:
            break
        for item in batch:
            row = item.get("row", {})
            rows.append(
                {
                    "prompt": row.get("prompt", ""),
                    "label": row.get("label", 0),
                }
            )
        print(f"  fetched {len(rows)} rows so far...", file=sys.stderr)
        offset += length
        if len(batch) < length:
            break
    return rows


def write_yaml(cases, path, header):
    with open(path, "w", encoding="utf-8") as f:
        f.write(header + "\n\n")
        yaml.dump(cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"  Wrote {len(cases)} cases to {path}", file=sys.stderr)


def main():
    print("Fetching hendzh/PromptShield (test split)...", file=sys.stderr)
    rows = fetch_rows()
    print(f"Total rows fetched: {len(rows)}", file=sys.stderr)

    attacks = []
    benign = []
    for i, row in enumerate(rows):
        text = row["prompt"].strip()
        if not text:
            continue
        case = {
            "id": f"promptshield-{i:04d}",
            "layer": "l3_inbound",
            "label": "malicious" if row["label"] == 1 else "benign",
            "description": f"PromptShield test row {i}",
            "content": text,
        }
        if row["label"] == 1:
            attacks.append(case)
        else:
            benign.append(case)

    print(f"Attacks: {len(attacks)}, Benign: {len(benign)}", file=sys.stderr)

    header_base = (
        "# hendzh/PromptShield — {kind}\n"
        "# Source: https://huggingface.co/datasets/hendzh/PromptShield\n"
        "# License: Apache-2.0\n"
        "# Auto-generated by scripts/fetch_promptshield.py"
    )

    write_yaml(attacks, "schema/eval/opensource_promptshield_attacks.yaml", header_base.format(kind="attacks (label=1)"))
    write_yaml(benign, "schema/eval/opensource_promptshield_benign.yaml", header_base.format(kind="benign (label=0)"))
    print("Done.", file=sys.stderr)


if __name__ == "__main__":
    main()
