"""
Download the full deepset/prompt-injections dataset from HuggingFace
and convert to parapet eval YAML format.

Source: https://huggingface.co/datasets/deepset/prompt-injections
662 prompts: 263 injections (label=1), 399 legitimate (label=0)
"""

import requests
import yaml
import sys

API = "https://datasets-server.huggingface.co/rows"
DATASET = "deepset/prompt-injections"
BATCH = 100

def fetch_all_rows():
    rows = []
    offset = 0
    while True:
        resp = requests.get(API, params={
            "dataset": DATASET,
            "config": "default",
            "split": "train",
            "offset": offset,
            "length": BATCH,
        })
        resp.raise_for_status()
        data = resp.json()
        batch = data.get("rows", [])
        if not batch:
            break
        for item in batch:
            row = item.get("row", {})
            rows.append({
                "text": row.get("text", ""),
                "label": row.get("label", 0),
            })
        print(f"  fetched {len(rows)} rows so far...", file=sys.stderr)
        offset += BATCH
        if len(batch) < BATCH:
            break
    return rows


def to_eval_cases(rows):
    attacks = []
    benign = []
    for i, row in enumerate(rows):
        text = row["text"].strip()
        if not text:
            continue
        case = {
            "id": f"deepset-{i:04d}",
            "layer": "l3_inbound",
            "label": "malicious" if row["label"] == 1 else "benign",
            "description": f"deepset row {i}",
            "content": text,
        }
        if row["label"] == 1:
            attacks.append(case)
        else:
            benign.append(case)
    return attacks, benign


def write_yaml(cases, path, header_comment):
    with open(path, "w", encoding="utf-8") as f:
        f.write(header_comment + "\n\n")
        yaml.dump(cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"  wrote {len(cases)} cases to {path}", file=sys.stderr)


def main():
    print("Fetching deepset/prompt-injections from HuggingFace...", file=sys.stderr)
    rows = fetch_all_rows()
    print(f"Total rows: {len(rows)}", file=sys.stderr)

    attacks, benign = to_eval_cases(rows)
    print(f"Attacks: {len(attacks)}, Benign: {len(benign)}", file=sys.stderr)

    write_yaml(
        attacks,
        "schema/eval/opensource_deepset_attacks.yaml",
        "# deepset/prompt-injections — attack cases (label=1)\n"
        "# Source: https://huggingface.co/datasets/deepset/prompt-injections\n"
        "# Auto-generated by scripts/fetch_deepset.py"
    )
    write_yaml(
        benign,
        "schema/eval/opensource_deepset_benign.yaml",
        "# deepset/prompt-injections — benign cases (label=0)\n"
        "# Source: https://huggingface.co/datasets/deepset/prompt-injections\n"
        "# Auto-generated by scripts/fetch_deepset.py"
    )
    print("Done.", file=sys.stderr)


if __name__ == "__main__":
    main()
