"""
Download a sample from Lakera/mosscap_prompt_injection from HuggingFace
and convert to parapet eval YAML format.

Source: https://huggingface.co/datasets/Lakera/mosscap_prompt_injection
223,533 injection attempts across Gandalf levels 1-8.
All prompts are injection attempts (no benign labels).

We sample ~2000 rows spread across the dataset to keep eval runtime reasonable.
"""

import requests
import yaml
import sys

API = "https://datasets-server.huggingface.co/rows"
DATASET = "Lakera/mosscap_prompt_injection"
BATCH = 100
TOTAL_ROWS = 223533
# Sample from 20 evenly-spaced offsets, 100 rows each = ~2000
SAMPLE_OFFSETS = [int(TOTAL_ROWS * i / 20) for i in range(20)]


def fetch_batch(offset):
    resp = requests.get(API, params={
        "dataset": DATASET,
        "config": "default",
        "split": "train",
        "offset": offset,
        "length": BATCH,
    })
    resp.raise_for_status()
    data = resp.json()
    rows = []
    for item in data.get("rows", []):
        row = item.get("row", {})
        rows.append(row.get("prompt", ""))
    return rows


def main():
    print("Fetching Lakera/mosscap_prompt_injection (sampled)...", file=sys.stderr)
    all_texts = []
    for i, offset in enumerate(SAMPLE_OFFSETS):
        texts = fetch_batch(offset)
        all_texts.extend(texts)
        print(f"  batch {i+1}/{len(SAMPLE_OFFSETS)} (offset={offset}): {len(texts)} rows, total={len(all_texts)}", file=sys.stderr)

    print(f"Total sampled: {len(all_texts)} rows", file=sys.stderr)

    # Deduplicate
    seen = set()
    cases = []
    for i, text in enumerate(all_texts):
        text = text.strip()
        if not text or text in seen:
            continue
        seen.add(text)
        cases.append({
            "id": f"mosscap-{i:04d}",
            "layer": "l3_inbound",
            "label": "malicious",
            "description": f"mosscap_prompt_injection sample {i}",
            "content": text,
        })

    path = "schema/eval/opensource_mosscap_attacks.yaml"
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "# Lakera/mosscap_prompt_injection — injection cases (sampled)\n"
            f"# Sampled ~{len(cases)} from 223,533 total rows\n"
            "# Source: https://huggingface.co/datasets/Lakera/mosscap_prompt_injection\n"
            "# Auto-generated by scripts/fetch_mosscap.py\n\n"
        )
        yaml.dump(cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"Wrote {len(cases)} cases to {path}", file=sys.stderr)


if __name__ == "__main__":
    main()
