# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Download xTRam1/safe-guard-prompt-injection from HuggingFace
and convert to parapet eval YAML format.

Source: https://huggingface.co/datasets/xTRam1/safe-guard-prompt-injection
License: Not declared
Paper:  https://arxiv.org/abs/2402.13064

~10K prompts (7K safe, 3K injection). Binary labels (1=injection, 0=safe).
Uses test split (2,060 rows).
"""

import requests
import yaml
import sys

API = "https://datasets-server.huggingface.co/rows"
DATASET = "xTRam1/safe-guard-prompt-injection"
CONFIG = "default"
SPLIT = "test"
BATCH = 100


def fetch_all_rows():
    rows = []
    offset = 0
    while True:
        resp = requests.get(
            API,
            params={
                "dataset": DATASET,
                "config": CONFIG,
                "split": SPLIT,
                "offset": offset,
                "length": BATCH,
            },
            timeout=30,
        )
        resp.raise_for_status()
        data = resp.json()
        batch = data.get("rows", [])
        if not batch:
            break
        for item in batch:
            row = item.get("row", {})
            rows.append(
                {
                    "text": row.get("text", ""),
                    "label": row.get("label", 0),
                }
            )
        print(f"  fetched {len(rows)} rows so far...", file=sys.stderr)
        offset += BATCH
        if len(batch) < BATCH:
            break
    return rows


def write_yaml(cases, path, header):
    with open(path, "w", encoding="utf-8") as f:
        f.write(header + "\n\n")
        yaml.dump(cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"  Wrote {len(cases)} cases to {path}", file=sys.stderr)


def main():
    print("Fetching xTRam1/safe-guard-prompt-injection (test split)...", file=sys.stderr)
    rows = fetch_all_rows()
    print(f"Total rows fetched: {len(rows)}", file=sys.stderr)

    attacks = []
    benign = []
    for i, row in enumerate(rows):
        text = row["text"].strip()
        if not text:
            continue
        case = {
            "id": f"safeguard-{i:04d}",
            "layer": "l3_inbound",
            "label": "malicious" if row["label"] == 1 else "benign",
            "description": f"safe-guard test row {i}",
            "content": text,
        }
        if row["label"] == 1:
            attacks.append(case)
        else:
            benign.append(case)

    print(f"Attacks: {len(attacks)}, Benign: {len(benign)}", file=sys.stderr)

    header_base = (
        "# xTRam1/safe-guard-prompt-injection — {kind}\n"
        "# Source: https://huggingface.co/datasets/xTRam1/safe-guard-prompt-injection\n"
        "# License: Not declared\n"
        "# Auto-generated by scripts/fetch_safeguard.py"
    )

    write_yaml(attacks, "schema/eval/opensource_safeguard_attacks.yaml", header_base.format(kind="attacks (label=1)"))
    write_yaml(benign, "schema/eval/opensource_safeguard_benign.yaml", header_base.format(kind="benign (label=0)"))
    print("Done.", file=sys.stderr)


if __name__ == "__main__":
    main()
