# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Download JailbreakBench/JBB-Behaviors from HuggingFace
and convert to parapet eval YAML format.

Source: https://huggingface.co/datasets/JailbreakBench/JBB-Behaviors
100 harmful behaviors + 100 benign behaviors.
"""

import requests
import yaml
import sys

API = "https://datasets-server.huggingface.co/rows"
DATASET = "JailbreakBench/JBB-Behaviors"
CONFIG = "behaviors"


def fetch_split(split):
    resp = requests.get(API, params={
        "dataset": DATASET,
        "config": CONFIG,
        "split": split,
        "offset": 0,
        "length": 100,
    })
    resp.raise_for_status()
    data = resp.json()
    rows = []
    for item in data.get("rows", []):
        row = item.get("row", {})
        rows.append({
            "goal": row.get("Goal", ""),
            "behavior": row.get("Behavior", ""),
            "category": row.get("Category", ""),
        })
    return rows


def main():
    print("Fetching JailbreakBench/JBB-Behaviors...", file=sys.stderr)

    harmful = fetch_split("harmful")
    print(f"  harmful: {len(harmful)} rows", file=sys.stderr)

    benign = fetch_split("benign")
    print(f"  benign: {len(benign)} rows", file=sys.stderr)

    attack_cases = []
    for i, row in enumerate(harmful):
        goal = row["goal"].strip()
        if not goal:
            continue
        attack_cases.append({
            "id": f"jbb-harmful-{i:03d}",
            "layer": "l3_inbound",
            "label": "malicious",
            "description": f"JailbreakBench harmful: {row['behavior']} ({row['category']})",
            "content": goal,
        })

    benign_cases = []
    for i, row in enumerate(benign):
        goal = row["goal"].strip()
        if not goal:
            continue
        benign_cases.append({
            "id": f"jbb-benign-{i:03d}",
            "layer": "l3_inbound",
            "label": "benign",
            "description": f"JailbreakBench benign: {row['behavior']} ({row['category']})",
            "content": goal,
        })

    attack_path = "schema/eval/opensource_jbb_attacks.yaml"
    with open(attack_path, "w", encoding="utf-8") as f:
        f.write(
            "# JailbreakBench/JBB-Behaviors — harmful behaviors\n"
            "# Source: https://huggingface.co/datasets/JailbreakBench/JBB-Behaviors\n"
            "# Auto-generated by scripts/fetch_jailbreakbench.py\n\n"
        )
        yaml.dump(attack_cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"Wrote {len(attack_cases)} attack cases to {attack_path}", file=sys.stderr)

    benign_path = "schema/eval/opensource_jbb_benign.yaml"
    with open(benign_path, "w", encoding="utf-8") as f:
        f.write(
            "# JailbreakBench/JBB-Behaviors — benign behaviors\n"
            "# Source: https://huggingface.co/datasets/JailbreakBench/JBB-Behaviors\n"
            "# Auto-generated by scripts/fetch_jailbreakbench.py\n\n"
        )
        yaml.dump(benign_cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"Wrote {len(benign_cases)} benign cases to {benign_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
