# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Download Dahoas/synthetic-hh-rlhf-prompts and Dahoas/hh_prompt_format
from HuggingFace and convert to parapet eval YAML format.

Sources:
  https://huggingface.co/datasets/Dahoas/synthetic-hh-rlhf-prompts
  https://huggingface.co/datasets/Dahoas/hh_prompt_format

Helpful/harmless RLHF prompts. All benign.
Used by ProtectAI for prompt injection detection training (negative class).

Samples up to 2000 entries per dataset.
"""

from datasets import load_dataset
import random
import yaml
import sys

MAX_SAMPLES = 2000


def fetch_one(dataset_name, id_prefix, text_fields, description):
    """Fetch and sample from a single dataset."""
    print(f"Loading {dataset_name}...", file=sys.stderr)
    try:
        ds = load_dataset(dataset_name, split="train")
    except Exception as e:
        print(f"  WARN: Could not load {dataset_name}: {e}", file=sys.stderr)
        return []

    print(f"  Total rows: {len(ds)}", file=sys.stderr)

    cases = []
    seen = set()
    for i, row in enumerate(ds):
        text = ""
        for field in text_fields:
            text = (row.get(field) or "").strip()
            if text:
                break
        if not text or text in seen:
            continue
        seen.add(text)
        cases.append({
            "id": f"{id_prefix}-{i:04d}",
            "layer": "l1",
            "label": "benign",
            "description": description,
            "content": text,
        })

    if len(cases) > MAX_SAMPLES:
        random.seed(42)
        cases = random.sample(cases, MAX_SAMPLES)
        for j, case in enumerate(cases):
            case["id"] = f"{id_prefix}-{j:04d}"

    print(f"  Benign cases: {len(cases)}", file=sys.stderr)
    return cases


def main():
    all_cases = []

    all_cases.extend(fetch_one(
        "Dahoas/synthetic-hh-rlhf-prompts",
        "dahoas-synth",
        ["prompt", "text", "input"],
        "Dahoas synthetic HH-RLHF",
    ))

    all_cases.extend(fetch_one(
        "Dahoas/hh_prompt_format",
        "dahoas-hh",
        ["prompt", "text", "input"],
        "Dahoas HH prompt format",
    ))

    print(f"\nTotal benign cases: {len(all_cases)}", file=sys.stderr)
    path = "schema/eval/opensource_dahoas_benign.yaml"
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "# Dahoas/synthetic-hh-rlhf-prompts + Dahoas/hh_prompt_format — RLHF prompts (all benign)\n"
            "# Sources: https://huggingface.co/datasets/Dahoas/synthetic-hh-rlhf-prompts\n"
            "#          https://huggingface.co/datasets/Dahoas/hh_prompt_format\n"
            "# Auto-generated by scripts/fetch_dahoas_hh.py\n\n"
        )
        yaml.dump(all_cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"  wrote {len(all_cases)} cases to {path}", file=sys.stderr)


if __name__ == "__main__":
    main()
