# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Download sahil2801/CodeAlpaca-20k from HuggingFace
and convert to parapet eval YAML format.

Source: https://huggingface.co/datasets/sahil2801/CodeAlpaca-20k
License: Apache-2.0

20K code instruction prompts. Used as benign training data —
code prompts contain injection-adjacent vocabulary ("execute",
"kill process", "inject", "override", "sudo") that cause FPs
in attack classifiers. Training on these immunizes specialists.

Requires: pip install datasets
"""

import random
import sys

import yaml

MAX_SAMPLES = 10000
SEED = 42


def main():
    from datasets import load_dataset

    print("Loading sahil2801/CodeAlpaca-20k...", file=sys.stderr)
    ds = load_dataset("sahil2801/CodeAlpaca-20k", split="train")
    print(f"  Loaded {len(ds)} rows", file=sys.stderr)

    # Combine instruction + input for richer text (input adds context)
    rows = []
    for row in ds:
        instruction = (row.get("instruction") or "").strip()
        inp = (row.get("input") or "").strip()
        if not instruction:
            continue
        text = f"{instruction}\n{inp}".strip() if inp and inp != "< noinput >" else instruction
        rows.append(text)

    # Sample if over max
    if len(rows) > MAX_SAMPLES:
        rng = random.Random(SEED)
        rows = rng.sample(rows, MAX_SAMPLES)

    print(f"  Selected {len(rows)} samples", file=sys.stderr)

    cases = []
    for i, text in enumerate(rows):
        cases.append({
            "id": f"codealpaca-{i:05d}",
            "layer": "l1",
            "label": "benign",
            "description": f"CodeAlpaca-20k code instruction",
            "content": text,
        })

    path = "schema/eval/opensource_codealpaca_benign.yaml"
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "# sahil2801/CodeAlpaca-20k — benign code instructions\n"
            "# Source: https://huggingface.co/datasets/sahil2801/CodeAlpaca-20k\n"
            "# License: Apache-2.0\n"
            f"# {len(cases)} code instruction prompts for FP reduction.\n"
            "# Auto-generated by scripts/fetch_codealpaca.py\n\n"
        )
        yaml.dump(cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"  Wrote {len(cases)} cases to {path}", file=sys.stderr)
    print("Done.", file=sys.stderr)


if __name__ == "__main__":
    main()
