# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Download jackhhao/jailbreak-classification from HuggingFace
and convert to parapet eval YAML format.

Source: https://huggingface.co/datasets/jackhhao/jailbreak-classification
~1044 prompts labeled as 'jailbreak' or 'benign'.
Good for L1 training and L3-inbound eval.
"""

from datasets import load_dataset
import yaml
import sys


def main():
    print("Loading jackhhao/jailbreak-classification...", file=sys.stderr)
    ds_train = load_dataset("jackhhao/jailbreak-classification", split="train")
    ds_test = load_dataset("jackhhao/jailbreak-classification", split="test")
    print(f"Train: {len(ds_train)}, Test: {len(ds_test)}", file=sys.stderr)

    attacks = []
    benign = []
    for i, row in enumerate(list(ds_train) + list(ds_test)):
        text = (row.get("prompt") or "").strip()
        if not text:
            continue
        is_jailbreak = (row.get("type") or "").lower() == "jailbreak"
        case = {
            "id": f"jailbreak-cls-{i:04d}",
            "layer": "l3_inbound",
            "label": "malicious" if is_jailbreak else "benign",
            "description": f"jailbreak-classification ({row.get('type', 'unknown')})",
            "content": text,
        }
        if is_jailbreak:
            attacks.append(case)
        else:
            benign.append(case)

    print(f"Attacks: {len(attacks)}, Benign: {len(benign)}", file=sys.stderr)

    for cases, label, filename in [
        (attacks, "jailbreak prompts", "opensource_jailbreak_cls_attacks.yaml"),
        (benign, "benign prompts", "opensource_jailbreak_cls_benign.yaml"),
    ]:
        path = f"schema/eval/{filename}"
        with open(path, "w", encoding="utf-8") as f:
            f.write(
                f"# jackhhao/jailbreak-classification — {label}\n"
                "# Source: https://huggingface.co/datasets/jackhhao/jailbreak-classification\n"
                "# Auto-generated by scripts/fetch_jailbreak_cls.py\n\n"
            )
            yaml.dump(cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
        print(f"  wrote {len(cases)} cases to {path}", file=sys.stderr)


if __name__ == "__main__":
    main()
