# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Download microsoft/llmail-inject-challenge from HuggingFace
and convert to parapet eval YAML format.

Source: https://huggingface.co/datasets/microsoft/llmail-inject-challenge
License: MIT

LLMail is a competition dataset of email-based indirect prompt injection
attacks (461K+ rows across Phase1 and Phase2).  All rows are attacks —
no benign split exists.

We sample a representative subset from Phase1 for eval.
"""

import requests
import yaml
import sys

API = "https://datasets-server.huggingface.co/rows"
DATASET = "microsoft/llmail-inject-challenge"
CONFIG = "default"
SPLIT = "Phase1"
MAX_ROWS = 2000
BATCH = 100


def fetch_rows():
    """Fetch up to MAX_ROWS from the dataset."""
    rows = []
    offset = 0
    while len(rows) < MAX_ROWS:
        length = min(BATCH, MAX_ROWS - len(rows))
        resp = requests.get(
            API,
            params={
                "dataset": DATASET,
                "config": CONFIG,
                "split": SPLIT,
                "offset": offset,
                "length": length,
            },
            timeout=30,
        )
        resp.raise_for_status()
        data = resp.json()
        batch = data.get("rows", [])
        if not batch:
            break
        for item in batch:
            row = item.get("row", {})
            rows.append(
                {
                    "subject": row.get("subject", ""),
                    "body": row.get("body", ""),
                    "objectives": row.get("objectives", ""),
                    "scenario": row.get("scenario", ""),
                }
            )
        print(f"  fetched {len(rows)} rows so far...", file=sys.stderr)
        offset += length
        if len(batch) < length:
            break
    return rows


def main():
    print("Fetching microsoft/llmail-inject-challenge (Phase1)...", file=sys.stderr)
    rows = fetch_rows()
    print(f"Total rows fetched: {len(rows)}", file=sys.stderr)

    attack_cases = []
    for i, row in enumerate(rows):
        body = row["body"].strip()
        subject = row["subject"].strip()
        if not body:
            continue

        # Combine subject + body as the injection payload.
        content = body
        if subject:
            content = f"Subject: {subject}\n\n{body}"

        # Truncate very long payloads for eval (some are 30K+ chars).
        if len(content) > 4000:
            content = content[:4000] + "\n[truncated]"

        attack_cases.append(
            {
                "id": f"llmail-{i:04d}",
                "layer": "l3_inbound",
                "label": "malicious",
                "description": f"LLMail inject: {row['objectives']} / {row['scenario']}",
                "content": content,
            }
        )

    print(f"Attack cases: {len(attack_cases)}", file=sys.stderr)

    path = "schema/eval/opensource_llmail_attacks.yaml"
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "# microsoft/llmail-inject-challenge — Phase1 sample (all attacks)\n"
            "# Source: https://huggingface.co/datasets/microsoft/llmail-inject-challenge\n"
            "# License: MIT\n"
            "# Auto-generated by scripts/fetch_llmail.py\n\n"
        )
        yaml.dump(attack_cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"Wrote {len(attack_cases)} cases to {path}", file=sys.stderr)
    print("Done.", file=sys.stderr)


if __name__ == "__main__":
    main()
