# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Download Lakera/gandalf_ignore_instructions from HuggingFace
and convert to parapet eval YAML format.

Source: https://huggingface.co/datasets/Lakera/gandalf_ignore_instructions
1,000 injection prompts across train/validation/test splits.
All prompts are injection attempts (no benign labels).
"""

import requests
import yaml
import sys

API = "https://datasets-server.huggingface.co/rows"
DATASET = "Lakera/gandalf_ignore_instructions"
BATCH = 100


def fetch_split(split):
    rows = []
    offset = 0
    while True:
        resp = requests.get(API, params={
            "dataset": DATASET,
            "config": "default",
            "split": split,
            "offset": offset,
            "length": BATCH,
        })
        resp.raise_for_status()
        data = resp.json()
        batch = data.get("rows", [])
        if not batch:
            break
        for item in batch:
            row = item.get("row", {})
            rows.append(row.get("text", ""))
        offset += BATCH
        if len(batch) < BATCH:
            break
    return rows


def main():
    print("Fetching Lakera/gandalf_ignore_instructions...", file=sys.stderr)
    all_texts = []
    for split in ["train", "validation", "test"]:
        texts = fetch_split(split)
        print(f"  {split}: {len(texts)} rows", file=sys.stderr)
        all_texts.extend(texts)

    print(f"Total: {len(all_texts)} rows", file=sys.stderr)

    cases = []
    for i, text in enumerate(all_texts):
        text = text.strip()
        if not text:
            continue
        cases.append({
            "id": f"gandalf-{i:04d}",
            "layer": "l3_inbound",
            "label": "malicious",
            "description": f"gandalf_ignore_instructions row {i}",
            "content": text,
        })

    path = "schema/eval/opensource_gandalf_attacks.yaml"
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "# Lakera/gandalf_ignore_instructions — injection cases\n"
            "# Source: https://huggingface.co/datasets/Lakera/gandalf_ignore_instructions\n"
            "# Auto-generated by scripts/fetch_gandalf.py\n\n"
        )
        yaml.dump(cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"Wrote {len(cases)} cases to {path}", file=sys.stderr)


if __name__ == "__main__":
    main()
