"""
Download fka/prompts.chat (formerly fka/awesome-chatgpt-prompts) from HuggingFace
and convert to parapet eval YAML format.

Source: https://huggingface.co/datasets/fka/prompts.chat
Creative system prompts — all benign. Good for L1 training negative class
and L3-inbound false-positive testing.
"""

from datasets import load_dataset
import yaml
import sys


def main():
    print("Loading fka/prompts.chat...", file=sys.stderr)
    ds = load_dataset("fka/prompts.chat", split="train")
    print(f"Total rows: {len(ds)}", file=sys.stderr)

    cases = []
    for i, row in enumerate(ds):
        text = (row.get("prompt") or "").strip()
        if not text:
            continue
        act = (row.get("act") or "unknown")[:60]
        cases.append({
            "id": f"prompts-chat-{i:04d}",
            "layer": "l3_inbound",
            "label": "benign",
            "description": f"prompts.chat: {act}",
            "content": text,
        })

    print(f"Benign cases: {len(cases)}", file=sys.stderr)
    path = "schema/eval/opensource_prompts_chat_benign.yaml"
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "# fka/prompts.chat — creative system prompts (all benign)\n"
            "# Source: https://huggingface.co/datasets/fka/prompts.chat\n"
            "# Auto-generated by scripts/fetch_prompts_chat.py\n\n"
        )
        yaml.dump(cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"  wrote {len(cases)} cases to {path}", file=sys.stderr)


if __name__ == "__main__":
    main()
