# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Download HuggingFaceH4/ultrachat_200k from HuggingFace
and convert to parapet eval YAML format.

Source: https://huggingface.co/datasets/HuggingFaceH4/ultrachat_200k
200K multi-topic conversations. All benign.
Used by ProtectAI for prompt injection detection training (negative class).

Samples 2000 first-turn user messages to keep the dataset manageable.
This is a large dataset — we only need a representative sample.
"""

from datasets import load_dataset
import random
import yaml
import sys

MAX_SAMPLES = 2000


def main():
    print("Loading HuggingFaceH4/ultrachat_200k (train_sft split)...", file=sys.stderr)
    try:
        ds = load_dataset("HuggingFaceH4/ultrachat_200k", split="train_sft")
    except Exception:
        print("  Trying 'train' split...", file=sys.stderr)
        ds = load_dataset("HuggingFaceH4/ultrachat_200k", split="train")
    print(f"Total rows: {len(ds)}", file=sys.stderr)

    cases = []
    seen = set()
    for i, row in enumerate(ds):
        # ultrachat has "messages" format — extract first user turn
        messages = row.get("messages", [])
        text = ""
        for msg in messages:
            if msg.get("role") == "user":
                text = (msg.get("content") or "").strip()
                break
        if not text:
            text = (row.get("prompt") or "").strip()
        if not text or text in seen:
            continue
        seen.add(text)
        cases.append({
            "id": f"ultrachat-{i:04d}",
            "layer": "l1",
            "label": "benign",
            "description": "ultrachat conversation",
            "content": text,
        })

    print(f"Benign cases (deduplicated): {len(cases)}", file=sys.stderr)

    if len(cases) > MAX_SAMPLES:
        random.seed(42)
        cases = random.sample(cases, MAX_SAMPLES)
        for j, case in enumerate(cases):
            case["id"] = f"ultrachat-{j:04d}"
        print(f"  sampled down to {MAX_SAMPLES}", file=sys.stderr)

    path = "schema/eval/opensource_ultrachat_benign.yaml"
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "# HuggingFaceH4/ultrachat_200k — multi-topic conversations (all benign)\n"
            "# Source: https://huggingface.co/datasets/HuggingFaceH4/ultrachat_200k\n"
            f"# Sampled {len(cases)} first-turn user messages from 200K conversations\n"
            "# Auto-generated by scripts/fetch_ultrachat.py\n\n"
        )
        yaml.dump(cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"  wrote {len(cases)} cases to {path}", file=sys.stderr)


if __name__ == "__main__":
    main()
