# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Download fka/awesome-chatgpt-prompts from HuggingFace
and convert to parapet eval YAML format.

Source: https://huggingface.co/datasets/fka/awesome-chatgpt-prompts
Community-curated ChatGPT system/role prompts. All benign.
Used by ProtectAI for prompt injection detection training (negative class).
"""

from datasets import load_dataset
import yaml
import sys


def main():
    print("Loading fka/awesome-chatgpt-prompts...", file=sys.stderr)
    ds = load_dataset("fka/awesome-chatgpt-prompts", split="train")
    print(f"Total rows: {len(ds)}", file=sys.stderr)

    cases = []
    seen = set()
    for i, row in enumerate(ds):
        text = (row.get("prompt") or row.get("text") or "").strip()
        if not text or text in seen:
            continue
        seen.add(text)
        cases.append({
            "id": f"awesome-chatgpt-{i:04d}",
            "layer": "l1",
            "label": "benign",
            "description": "awesome-chatgpt-prompts",
            "content": text,
        })

    print(f"Benign cases: {len(cases)}", file=sys.stderr)
    path = "schema/eval/opensource_awesome_chatgpt_benign.yaml"
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "# fka/awesome-chatgpt-prompts — community role prompts (all benign)\n"
            "# Source: https://huggingface.co/datasets/fka/awesome-chatgpt-prompts\n"
            "# Auto-generated by scripts/fetch_awesome_chatgpt.py\n\n"
        )
        yaml.dump(cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"  wrote {len(cases)} cases to {path}", file=sys.stderr)


if __name__ == "__main__":
    main()
