# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Download hackaprompt/hackaprompt-dataset from HuggingFace
and convert to parapet eval YAML format.

Source: https://huggingface.co/datasets/hackaprompt/hackaprompt-dataset
Competition entries from 2,800+ participants with 600K+ adversarial prompts.
Diverse prompt injection techniques across difficulty levels.

GATED DATASET: Requires HF_TOKEN environment variable.
  export HF_TOKEN=hf_xxxxx
"""

from datasets import load_dataset
import yaml
import sys
import os
import random

MAX_CASES = 2000


def main():
    token = os.environ.get("HF_TOKEN", "")
    if not token:
        from huggingface_hub import HfFolder
        token = HfFolder.get_token()
    if not token:
        print("ERROR: hackaprompt dataset is gated. Set HF_TOKEN env var", file=sys.stderr)
        print("  or run `huggingface-cli login`.", file=sys.stderr)
        sys.exit(1)

    print("Loading hackaprompt/hackaprompt-dataset...", file=sys.stderr)
    ds = load_dataset("hackaprompt/hackaprompt-dataset", split="train", token=token)
    print(f"Total rows: {len(ds)}", file=sys.stderr)
    print(f"Columns: {ds.column_names}", file=sys.stderr)

    # Discover the prompt field name
    prompt_field = None
    for candidate in ["user_input", "prompt", "text", "content"]:
        if candidate in ds.column_names:
            prompt_field = candidate
            break
    if not prompt_field:
        print(f"ERROR: Could not find prompt field. Columns: {ds.column_names}", file=sys.stderr)
        sys.exit(1)
    print(f"Using prompt field: {prompt_field}", file=sys.stderr)

    # Sample and deduplicate
    indices = list(range(len(ds)))
    random.seed(42)
    random.shuffle(indices)

    cases = []
    seen = set()
    for idx in indices:
        if len(cases) >= MAX_CASES:
            break
        row = ds[idx]
        text = str(row.get(prompt_field) or "").strip()
        if not text or len(text) < 10 or text in seen:
            continue
        seen.add(text)

        level = row.get("level", "unknown")
        model = row.get("model", "unknown")

        cases.append({
            "id": f"hackaprompt-{len(cases):04d}",
            "layer": "l3_inbound",
            "label": "malicious",
            "description": f"HackAPrompt level={level} model={model}",
            "content": text,
        })

    print(f"Attack cases: {len(cases)}", file=sys.stderr)
    path = "schema/eval/opensource_hackaprompt_attacks.yaml"
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "# hackaprompt/hackaprompt-dataset — competition prompt injections\n"
            "# Source: https://huggingface.co/datasets/hackaprompt/hackaprompt-dataset\n"
            f"# Sampled {len(cases)} diverse injection techniques\n"
            "# Auto-generated by scripts/fetch_hackaprompt.py\n\n"
        )
        yaml.dump(cases, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"  wrote {len(cases)} cases to {path}", file=sys.stderr)


if __name__ == "__main__":
    main()
