#!/usr/bin/env python3
# Copyright 2026 The Parapet Project
# SPDX-License-Identifier: Apache-2.0

"""
Generate a publishable EN indirect_injection specialist file from staged LLMail.

Run from the parapet/ directory.

This fills the v5 mirror gap with a deterministic subset of staged LLMail rows
that are already labeled as `indirect_injection`. The generator keeps only
rows that look publishable and preserves deterministic ordering through a fixed
seed shuffle.
"""

from __future__ import annotations

import argparse
import hashlib
import random
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

import yaml


def load_rows(path: Path) -> list[dict]:
    rows = yaml.safe_load(path.read_text(encoding="utf-8")) or []
    if not isinstance(rows, list):
        raise ValueError(f"{path}: expected top-level YAML list")
    return rows


def is_publishable_candidate(row: dict) -> bool:
    if row.get("label") != "malicious":
        return False
    if row.get("reason") != "indirect_injection":
        return False

    text = str(row.get("content", "")).strip()
    if not text:
        return False
    if len(text) < 120 or len(text) > 12000:
        return False

    lowered = text.lower()
    if not any(
        token in lowered
        for token in (
            "contact@",
            "contact[at]",
            "send email",
            "send an email",
            "email to",
            "sendmail",
            "tool call",
            "api_call",
            "api call",
            'body "confirmation"',
            "body is the string",
            "profit forecast",
        )
    ):
        return False

    if any(bad in text for bad in ("â", "ðŸ", "\ufffd")):
        return False

    non_ascii = sum(1 for char in text if ord(char) > 127)
    if non_ascii / len(text) > 0.06:
        return False

    return True


def content_hash(text: str) -> str:
    return hashlib.sha256(text.strip().encode("utf-8")).hexdigest()


def build_cases(rows: list[dict], max_samples: int, seed: int) -> tuple[list[dict], dict]:
    reason_rows = [row for row in rows if row.get("reason") == "indirect_injection"]
    filtered = [row for row in reason_rows if is_publishable_candidate(row)]

    deduped: dict[str, dict] = {}
    for row in filtered:
        deduped.setdefault(content_hash(str(row["content"])), row)

    shuffled = list(deduped.values())
    random.Random(seed).shuffle(shuffled)
    selected = shuffled[:max_samples]

    cases = []
    for row in selected:
        digest = content_hash(str(row["content"]))
        cases.append(
            {
                "id": f"indirect-llmail-{digest[:12]}",
                "layer": "l3_inbound",
                "label": "malicious",
                "description": "LLMail staged indirect injection",
                "content": row["content"],
            }
        )

    summary = {
        "input_rows": len(rows),
        "reason_rows": len(reason_rows),
        "publishable_candidates": len(filtered),
        "deduped_candidates": len(deduped),
        "selected_rows": len(cases),
        "source_distribution": dict(sorted(Counter(row.get("source", "") for row in selected).items())),
        "seed": seed,
        "max_samples": max_samples,
    }
    return cases, summary


def write_output(cases: list[dict], summary: dict, out_path: Path) -> None:
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    source_lines = "\n".join(f"#   {name}: {count}" for name, count in summary["source_distribution"].items())
    if not source_lines:
        source_lines = "#   (none)"

    with out_path.open("w", encoding="utf-8") as handle:
        handle.write(
            "# L1 specialist training data: indirect_injection\n"
            "# Auto-generated by scripts/generate_indirect_injection_specialist.py\n"
            f"# Generated: {timestamp}\n"
            f"# Selected {summary['selected_rows']} attack samples from {summary['deduped_candidates']} deduped publishable candidates\n"
            f"# Source indirect_injection staged rows: {summary['reason_rows']}\n"
            "# Source distribution:\n"
            f"{source_lines}\n\n"
        )
        yaml.dump(cases, handle, default_flow_style=False, allow_unicode=True, sort_keys=False)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("schema/eval/staging/en_llmail-inject-challenge_attacks_staged.yaml"),
        help="Input staged YAML (default: schema/eval/staging/en_llmail-inject-challenge_attacks_staged.yaml)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("schema/eval/staging/en_indirect_injection_attacks_staged.yaml"),
        help="Output YAML (default: schema/eval/staging/en_indirect_injection_attacks_staged.yaml)",
    )
    parser.add_argument("--max-samples", type=int, default=400)
    parser.add_argument("--seed", type=int, default=42)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    rows = load_rows(args.input)
    cases, summary = build_cases(rows, max_samples=args.max_samples, seed=args.seed)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    write_output(cases, summary, args.output)
    print(summary)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
